# -*- coding: utf-8 -*-
from . import base_dictionary
from . import project_core
from . import document_center
from . import contract_center
from . import project_contract
from . import cost_domain
from . import purchase_extend
from . import account_extend
from . import stock_extend
from . import product_extend
from . import cost_report
from . import profit_report
from . import task_extend
from . import work_breakdown
from . import boq
from . import tender
from . import res_config_settings
from . import account_move_line_ext
