#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCENE_CATALOG_JSON = ROOT / "docs" / "contract" / "exports" / "scene_catalog.json"
SCENE_MATRIX_JSON = ROOT / "artifacts" / "backend" / "scene_capability_matrix_report.json"

REPORT_JSON = ROOT / "artifacts" / "backend" / "catalog_runtime_explain_report.json"
REPORT_MD = ROOT / "docs" / "ops" / "audit" / "catalog_runtime_explain_report.md"


def _load_json(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _classify(scene_key: str, catalog_scene_keys: set[str]) -> tuple[str, str]:
    if scene_key in catalog_scene_keys:
        return "catalog", "listed in scene_catalog export"
    if "__pkg" in scene_key:
        return "derived", "derived scene variant generated by package suffix"
    if scene_key.startswith("default") or scene_key.startswith("scene_smoke_default"):
        return "system", "system shell/default scene family"
    if scene_key.startswith("portal.") or scene_key.startswith("projects.") or scene_key.startswith("finance.") or scene_key.startswith("cost.") or scene_key.startswith("data."):
        return "system", "runtime system scene outside contract snapshot subset"
    return "fallback", "runtime fallback/legacy naming path"


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    scene_catalog = _load_json(SCENE_CATALOG_JSON)
    scene_matrix = _load_json(SCENE_MATRIX_JSON)

    catalog_rows = scene_catalog.get("scenes") if isinstance(scene_catalog.get("scenes"), list) else []
    catalog_scene_keys = {
        str(item.get("scene_key") or "").strip()
        for item in catalog_rows
        if isinstance(item, dict) and str(item.get("scene_key") or "").strip()
    }
    runtime_scene_keys = {
        str(x or "").strip()
        for x in (scene_matrix.get("scene_keys") if isinstance(scene_matrix.get("scene_keys"), list) else [])
        if str(x or "").strip()
    }

    if not catalog_scene_keys:
        errors.append("catalog scene keys empty")
    if not runtime_scene_keys:
        errors.append("runtime scene keys empty")

    rows = []
    source_counter = {"catalog": 0, "derived": 0, "system": 0, "fallback": 0}
    unknown_source = []
    for scene_key in sorted(runtime_scene_keys):
        source, reason = _classify(scene_key, catalog_scene_keys)
        if source not in source_counter:
            unknown_source.append(scene_key)
            source = "fallback"
            reason = "unknown classification fallback"
        source_counter[source] += 1
        rows.append({"scene_key": scene_key, "source": source, "reason": reason})

    if unknown_source:
        errors.append(f"unknown_source_count={len(unknown_source)}")

    coverage_ratio = round((source_counter["catalog"] / len(runtime_scene_keys)), 6) if runtime_scene_keys else 0.0
    report = {
        "ok": len(errors) == 0,
        "summary": {
            "catalog_scene_count": len(catalog_scene_keys),
            "runtime_scene_count": len(runtime_scene_keys),
            "source_catalog_count": source_counter["catalog"],
            "source_derived_count": source_counter["derived"],
            "source_system_count": source_counter["system"],
            "source_fallback_count": source_counter["fallback"],
            "unknown_source_count": len(unknown_source),
            "catalog_runtime_coverage_ratio": coverage_ratio,
            "error_count": len(errors),
            "warning_count": len(warnings),
        },
        "rows": rows,
        "errors": errors,
        "warnings": warnings,
    }

    REPORT_JSON.parent.mkdir(parents=True, exist_ok=True)
    REPORT_JSON.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Catalog Runtime Explain Report",
        "",
        f"- catalog_scene_count: {len(catalog_scene_keys)}",
        f"- runtime_scene_count: {len(runtime_scene_keys)}",
        f"- source_catalog_count: {source_counter['catalog']}",
        f"- source_derived_count: {source_counter['derived']}",
        f"- source_system_count: {source_counter['system']}",
        f"- source_fallback_count: {source_counter['fallback']}",
        f"- unknown_source_count: {len(unknown_source)}",
        f"- catalog_runtime_coverage_ratio: {coverage_ratio}",
        f"- error_count: {len(errors)}",
        "",
        "## Runtime Scene Source Mapping",
        "",
    ]
    for row in rows:
        lines.append(f"- {row['scene_key']} -> {row['source']} ({row['reason']})")

    REPORT_MD.parent.mkdir(parents=True, exist_ok=True)
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(str(REPORT_MD))
    print(str(REPORT_JSON))
    if errors:
        print("[catalog_runtime_explain_report] FAIL")
        return 2
    print("[catalog_runtime_explain_report] PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

