#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCAN_DIRS = [
    ROOT / "frontend" / "apps" / "web" / "src" / "app",
    ROOT / "frontend" / "apps" / "web" / "src" / "app" / "action_runtime",
    ROOT / "frontend" / "apps" / "web" / "src" / "app" / "assemblers",
    ROOT / "frontend" / "apps" / "web" / "src" / "app" / "contracts",
    ROOT / "frontend" / "apps" / "web" / "src" / "app" / "suggested_action",
    ROOT / "frontend" / "apps" / "web" / "src" / "api",
    ROOT / "frontend" / "apps" / "web" / "src" / "components",
    ROOT / "frontend" / "apps" / "web" / "src" / "composables",
    ROOT / "frontend" / "apps" / "web" / "src" / "config",
    ROOT / "frontend" / "apps" / "web" / "src" / "layouts",
    ROOT / "frontend" / "apps" / "web" / "src" / "pages",
    ROOT / "frontend" / "apps" / "web" / "src" / "router",
    ROOT / "frontend" / "apps" / "web" / "src" / "stores",
    ROOT / "frontend" / "apps" / "web" / "src" / "views",
]
SCAN_SUFFIXES = {".ts", ".tsx", ".js", ".jsx", ".vue"}

FORBIDDEN_PHRASES = {
    "待完善配置": "用户界面不能暴露工程整改口径，应使用产品状态口径",
    "待完善：": "用户界面不能用工程整改汇总，应使用明确状态",
    "当前待完善项": "用户界面不能要求用户理解后台配置缺口",
    "配置缺口提示": "用户界面提示应表达配置状态，而不是工程缺口",
    "后端配置缺口": "用户界面不能暴露后端实现边界",
    "后端兜底": "用户界面不能暴露兜底实现机制",
    "Scene Packages": "管理员页面标题必须使用产品化中文表达",
    "Loading packages": "管理员页面加载状态必须使用产品化中文表达",
    "Package operation failed": "管理员页面错误状态必须使用产品化中文表达",
    "Installed Packages": "管理员页面区块标题必须使用产品化中文表达",
    "Import Package": "管理员页面操作标题必须使用产品化中文表达",
    "Package JSON": "管理员页面字段标签必须使用产品化中文表达",
    "Reason (required)": "管理员页面必填说明必须使用产品化中文表达",
    "Dry Run": "管理员页面操作按钮必须使用产品化中文表达",
    "Export Package": "管理员页面操作标题必须使用产品化中文表达",
    "Scene Health Dashboard": "管理员页面标题必须使用产品化中文表达",
    "Loading scene health": "管理员页面加载状态必须使用产品化中文表达",
    "Governance Actions": "管理员页面区块标题必须使用产品化中文表达",
    "Target Channel": "管理员页面字段标签必须使用产品化中文表达",
    "Set Channel": "管理员页面操作按钮必须使用产品化中文表达",
    "Pin Stable": "管理员页面操作按钮必须使用产品化中文表达",
    "Export Contract": "管理员页面操作按钮必须使用产品化中文表达",
    "Confirm import scene package": "确认弹窗必须使用产品化中文表达",
    "Confirm rollback to stable pinned mode": "确认弹窗必须使用产品化中文表达",
    "reason is required": "表单校验提示必须使用产品化中文表达",
    "health request failed": "页面错误提示必须使用产品化中文表达",
    "Copy trace": "通用状态面板按钮必须使用产品化中文表达",
    ">Retry<": "通用状态面板按钮必须使用产品化中文表达",
    "Add line": "关联明细操作必须使用产品化中文表达",
    "No related records": "关联明细空状态必须使用产品化中文表达",
    "Loading related records": "关联明细加载状态必须使用产品化中文表达",
    "Add related record": "关联明细弹窗标题必须使用产品化中文表达",
    "Edit related record": "关联明细弹窗标题必须使用产品化中文表达",
    "Delete this related record": "确认弹窗必须使用产品化中文表达",
    "Usage Analytics": "管理员分析页面标题必须使用产品化中文表达",
    "Loading usage report": "管理员分析页面加载状态必须使用产品化中文表达",
    "Failed to load usage report": "管理员分析页面错误状态必须使用产品化中文表达",
    "Scene Open Total": "管理员分析页面统计卡片必须使用产品化中文表达",
    "Capability Open Total": "管理员分析页面统计卡片必须使用产品化中文表达",
    "Generated At": "管理员分析页面统计卡片必须使用产品化中文表达",
    "Top Scenes": "管理员分析页面表格标题必须使用产品化中文表达",
    "Top Capabilities": "管理员分析页面表格标题必须使用产品化中文表达",
    "Visibility Reason Counts": "管理员分析页面表格标题必须使用产品化中文表达",
    "Hidden Capability Samples": "管理员分析页面表格标题必须使用产品化中文表达",
    "{{ item.reason_code }} ({{ item.count }})": "管理员分析页原因筛选必须展示产品化标签",
    "<td>{{ item.reason_code }}</td>": "管理员分析页原因统计必须展示产品化标签",
    "{{ item.reason_code || item.reason || '-' }}": "管理员分析页隐藏样例必须展示产品化标签",
    "${scope || '未归类'} / ${issue.reasonCode}": "管理员分析页错误上下文必须展示产品化原因标签",
    "Resolving menu": "菜单解析页面加载状态必须使用产品化中文表达",
    "Menu group": "菜单解析页面状态标题必须使用产品化中文表达",
    "Menu resolve failed": "菜单解析页面错误状态必须使用产品化中文表达",
    "resolve menu failed": "菜单解析页面错误信息必须使用产品化中文表达",
    "invalid menu id": "菜单解析页面错误信息必须使用产品化中文表达",
    "Dynamic View Placeholder": "占位页面必须使用产品化中文表达",
    "Record Context": "记录详情页诊断标题必须使用产品化中文表达",
    "Loading record": "记录详情页加载状态必须使用产品化中文表达",
    "Saving record": "记录详情页保存状态必须使用产品化中文表达",
    "View node unsupported": "记录详情页错误状态必须使用产品化中文表达",
    "Saved. Changes have been applied.": "记录详情页保存反馈必须使用产品化中文表达",
    "Record load failed": "记录详情页错误状态必须使用产品化中文表达",
    "Failed to load chatter": "记录详情页协作错误必须使用产品化中文表达",
    "Failed to post chatter message": "记录详情页协作错误必须使用产品化中文表达",
    "Failed to upload file": "记录详情页附件错误必须使用产品化中文表达",
    "Failed to download file": "记录详情页附件错误必须使用产品化中文表达",
    "failed to load record": "记录详情页错误状态必须使用产品化中文表达",
    "failed to execute button": "记录详情页操作错误必须使用产品化中文表达",
    "failed to save record": "记录详情页保存错误必须使用产品化中文表达",
    "scene render target missing": "场景页错误状态必须使用产品化中文表达",
    "scene resolve failed": "场景页错误状态必须使用产品化中文表达",
    "Release Operator Surface": "发布运营页面标题必须使用产品化中文表达",
    "Active Released Snapshot": "发布运营页面指标必须使用产品化中文表达",
    "Latest Action": "发布运营页面指标必须使用产品化中文表达",
    "Approval State": "发布运营页面指标必须使用产品化中文表达",
    ">draft<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">preview<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">stable<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">archived<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">public<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">internal<": "发布运营页面枚举选项必须使用产品化中文表达",
    ">role_restricted<": "发布运营页面枚举选项必须使用产品化中文表达",
    "retry_unknown_reason_code', 'UNKNOWN": "我的工作台失败原因默认值必须使用产品化中文表达",
    "trace_id 已复制": "我的工作台复制反馈必须使用产品化中文表达",
    "复制 trace_id 失败": "我的工作台复制反馈必须使用产品化中文表达",
    "Retry failed items from my-work": "我的工作台重试备注必须使用产品化中文表达",
    "Retry failed group": "我的工作台重试备注必须使用产品化中文表达",
    "显示模式: ": "我的工作台复制摘要必须使用产品化中文表达",
    "retry_visible_display_grouped', 'grouped": "我的工作台复制摘要不得暴露英文显示模式",
    "retry_visible_display_flat', 'flat": "我的工作台复制摘要不得暴露英文显示模式",
    "{{ item.reason_code }} x {{ item.count }}": "我的工作台失败原因分布必须展示产品化标签",
    "{{ group.reason_code }} ({{ group.count }}": "我的工作台失败原因分组必须展示产品化标签",
    "{{ item.reason_code || pageText('retry_unknown_reason_code'": "我的工作台失败明细必须展示产品化标签",
    "`#${item.id} ${item.reason_code || pageText('retry_unknown_reason_code'": "我的工作台失败摘要必须展示产品化标签",
    "${item.reason_code}${pageText('retry_summary_group_count_sep'": "我的工作台失败原因摘要必须展示产品化标签",
    "feedback_filtered_by_reason_prefix', '已按失败原因筛选：')}${reasonCode}": "我的工作台失败原因筛选反馈必须展示产品化标签",
    "${reasonCode}${pageText('feedback_reason_group_no_retry_suffix'": "我的工作台失败原因反馈必须展示产品化标签",
    "retry_note_default_failed_group_prefix', '从我的工作台重试失败原因组：')}${reasonCode}": "我的工作台失败原因重试备注必须展示产品化标签",
    "batch_action_retry_group_left', '重试(')}${reasonCode}": "我的工作台失败原因重试按钮必须展示产品化标签",
    "Refresh now": "建议动作默认按钮必须使用产品化中文表达",
    "Retry now": "建议动作默认按钮必须使用产品化中文表达",
    "Copy trace": "建议动作默认按钮必须使用产品化中文表达",
    "Refresh the latest data and retry.": "建议动作默认说明必须使用产品化中文表达",
    "Copy trace id for troubleshooting.": "建议动作默认说明必须使用产品化中文表达",
    "Authentication required": "通用错误标题必须使用产品化中文表达",
    "Permission denied": "通用错误标题必须使用产品化中文表达",
    "Invalid request": "通用错误标题必须使用产品化中文表达",
    "Write conflict": "通用错误标题必须使用产品化中文表达",
    "Business rule blocked": "通用错误标题必须使用产品化中文表达",
    "System exception": "通用错误标题必须使用产品化中文表达",
    "Network error": "通用错误标题必须使用产品化中文表达",
    "Request failed": "通用错误标题必须使用产品化中文表达",
    "No work items": "通用空状态必须使用产品化中文表达",
    "No records returned for this action.": "通用空状态必须使用产品化中文表达",
    "return `Context:": "通用错误上下文必须使用产品化中文表达",
    "trace_id={{": "首页入口错误诊断信息必须使用产品化中文表达",
    "label: 'trace_id'": "HUD 标签必须使用产品化中文表达",
    "label: 'record_id'": "HUD 标签必须使用产品化中文表达",
    "Loading cards...": "看板页加载状态必须使用产品化中文表达",
    "Card load failed": "看板页错误状态必须使用产品化中文表达",
    "scene.health response missing": "场景健康契约错误必须转换为产品化中文表达",
    "scene.health missing key": "场景健康契约错误必须转换为产品化中文表达",
    "scene.health.summary critical counters missing": "场景健康契约错误必须转换为产品化中文表达",
    "scene.health.details arrays missing": "场景健康契约错误必须转换为产品化中文表达",
    "页面地址') }}:": "占位页字段展示必须使用中文标点",
    "页面参数') }}:": "占位页字段展示必须使用中文标点",
    "empty contract": "表单契约错误必须转换为产品化中文表达",
    "contract surface markers invalid": "表单契约错误必须转换为产品化中文表达",
    "form config audit failed": "表单页错误兜底必须使用产品化中文表达",
    "action execute failed": "表单页错误兜底必须使用产品化中文表达",
    "chatter timeline load failed": "表单页协作错误兜底必须使用产品化中文表达",
    "chatter post failed": "表单页协作错误兜底必须使用产品化中文表达",
    "chatter activity schedule failed": "表单页协作错误兜底必须使用产品化中文表达",
    "'load failed'": "表单页错误兜底必须使用产品化中文表达",
    "unknown render error": "表单页渲染错误必须使用产品化中文表达",
    "ContractFormPage render error": "表单页渲染错误必须使用产品化中文表达",
    "ActionView render error": "列表页渲染错误必须使用产品化中文表达",
    "contract action failed": "表单页配置操作错误必须使用产品化中文表达",
    "field policy update failed": "表单页字段配置错误必须使用产品化中文表达",
    "custom field create failed": "表单页字段配置错误必须使用产品化中文表达",
    "field order update failed": "表单页字段配置错误必须使用产品化中文表达",
    "contract open action missing action_id": "表单页打开操作错误必须使用产品化中文表达",
    "scene mutation execute failed": "表单页场景操作错误必须使用产品化中文表达",
    "contract not renderable": "表单契约错误必须转换为产品化中文表达",
    "Failed to load my work": "我的工作台错误兜底必须使用产品化中文表达",
    "Legacy List Route": "列表入口页面必须使用产品化中文表达",
    "contract-driven ActionView": "列表入口页面不能暴露前端实现名称",
    "View Context": "页面诊断标题必须使用产品化中文表达",
    "block_type={{": "页面区块兜底不能暴露工程字段名",
    "'unknown error'": "页面错误兜底必须使用产品化中文表达",
    "unknown v2 contract decode error": "表单契约解析错误必须使用产品化中文表达",
    "能力包 JSON": "能力包页面字段标签必须使用产品化中文表达",
    "场景能力包 JSON": "能力包页面占位说明必须使用产品化中文表达",
    "快照 JSON": "配置快照页面错误提示必须使用产品化中文表达",
    "make verify.business_config.snapshot": "配置工作台不能在用户界面暴露工程命令",
    "make verify.lowcode_config.runtime_boundary.guard": "配置工作台不能在用户界面暴露工程命令",
    "make verify.product.surface.clean": "配置工作台不能在用户界面暴露工程命令",
    "Only ui.business.config.contract": "配置整改清单必须使用产品化中文表达",
    "This plan is review evidence": "配置整改清单必须使用产品化中文表达",
    "hud_value_na', 'N/A": "诊断面板空值必须使用产品化中文表达",
    "type={{": "诊断面板不能暴露工程字段名",
    "例如 action_id": "工作台提示不能暴露工程字段名",
    "License:": "授权提示必须使用产品化中文表达",
    "advisory-only": "场景交付提示不能暴露工程阶段术语",
    "direct delivery": "场景交付提示不能暴露工程阶段术语",
    "scope || 'unknown'": "分析页面错误上下文必须使用产品化中文表达",
    "导出重试 JSON": "我的工作台操作按钮必须使用产品化中文表达",
    "复制 Trace": "我的工作台操作按钮必须使用产品化中文表达",
    "导出失败 CSV": "我的工作台操作按钮必须使用产品化中文表达",
    "重试请求 JSON": "我的工作台反馈必须使用产品化中文表达",
    "<pre>{{ retryRequestJson }}</pre>": "我的工作台重试预览必须使用产品化摘要",
    "失败明细 CSV": "我的工作台反馈必须使用产品化中文表达",
    "当前 License": "授权提示必须使用产品化中文表达",
    "导出 CSV": "分析页面操作按钮必须使用产品化中文表达",
    "Scene 能力包": "能力包页面说明必须使用产品化中文表达",
    "JSON.stringify(packages": "能力包页面不能直接展示原始结构数据",
    "JSON.stringify(dryRunResult": "能力包预检查结果必须使用产品化摘要",
    "<pre v-if=\"exportResult\"": "能力包导出结果必须使用产品化摘要",
    "JSON.stringify(health.details": "场景健康明细必须使用产品化清单",
    "replay_audit_id:": "我的工作台重放审计信息必须使用产品化中文表达",
    "replay_age_ms:": "我的工作台重放耗时必须使用产品化中文表达",
    "payload.action || 'unknown'": "我的工作台建议动作反馈必须使用产品化兜底",
    "已触发=": "场景健康状态必须使用产品化中文标点与表达",
    "reason_codes.length ? value.reason_codes.join": "场景健康自动调整原因必须展示产品化摘要",
    "autoCodes.length ? autoCodes.join": "场景健康治理原因必须展示产品化摘要",
    "兼容配置": "场景健康运行来源必须使用产品化发布口径",
    "历史兼容": "场景健康运行来源必须使用产品化发布口径",
    "区块类型：{{ block.block_type": "页面区块兜底不能暴露工程字段名",
    "未支持的区块类型": "页面区块兜底不能向用户暴露结构类型概念",
    "{{ block.kind }}": "场景区块预览不能直接展示结构类型编码",
    "typeof value === 'object' ? JSON.stringify(value)": "通用页面区块不能直接展示结构数据",
    "if (typeof value === 'object') return JSON.stringify(value);": "通用页面表格不能直接展示结构数据",
    "模式: ": "我的工作台状态标签必须使用中文标点",
    "命中重放#": "我的工作台重放反馈必须使用产品化中文表达",
    "Export SA": "页面诊断操作必须使用产品化中文表达",
    "Extraction stats": "页面诊断反馈必须使用产品化中文表达",
    "suggested_action traces": "页面诊断导出反馈必须使用产品化中文表达",
    "label: 'scene_key'": "页面诊断标签必须使用产品化中文表达",
    "governance.runtime_source": "页面诊断标签必须使用产品化中文表达",
    "JSON.stringify(layoutStats": "记录页诊断信息必须使用产品化摘要",
    "({{ actionFeedback.reasonCode }})": "记录操作反馈必须展示产品化原因标签",
    "batch_error_reason_prefix', '原因='": "列表批量错误摘要必须使用中文标点",
    "${options.text('batch_error_reason_prefix', '原因=')}${issue.reasonCode}": "列表批量错误摘要必须展示产品化原因标签",
    "原因：{{ reasonCode }}": "通用错误状态面板必须展示产品化原因标签",
    "[${reason}]": "通用错误状态面板普通用户上下文不能暴露工程原因码",
    "原因码: ${reasonCode}": "表单联动提示必须展示产品化原因标签",
    "联动状态: ${rowState}": "表单联动提示不能暴露运行时状态码",
    "命令提示: ${patch.command_hint.join('/')": "表单联动提示不能暴露底层命令码",
    "筛选失败明细：ID / 原因码 / 消息": "我的工作台失败搜索不能暴露原因码字段名",
    "页面暂未配置": "占位页面必须使用可交付空状态口径",
    "页面地址') }}：{{ route.path }}": "占位页面不能向用户暴露路由地址",
    "页面参数') }}：{{ routeParamsText }}": "占位页面不能向用户暴露路由参数",
    "placeholder=\"res.partner\"": "配置工作台业务对象输入不能用技术模型示例",
    "placeholder=\"可选 role_key\"": "配置工作台角色范围输入不能暴露工程字段名",
    "<span>页面ID</span>": "配置工作台范围字段必须使用产品化编号口径",
    "<span>视图ID</span>": "配置工作台范围字段必须使用产品化编号口径",
    "需补 {{ row.missing_view_types": "配置工作台列表状态必须使用产品化任务口径",
    "运行时未命中 {{ row.runtime_missing_view_types": "配置工作台列表状态不能暴露运行时命中口径",
    "return `需补 ${missingContractTypes": "配置工作台行操作提示必须使用产品化任务口径",
    "localStorage.getItem('DEBUG_INTENT')": "生产构建不能通过本地存储打开初始化诊断",
    "new URLSearchParams(window.location.search).get('debug')": "生产构建不能通过 URL 打开初始化诊断",
    "localStorage.getItem('__HUD__')": "生产构建不能通过本地存储打开 HUD 诊断",
    "localStorage.getItem('__SCENE_BLOCKS__')": "生产构建不能通过本地存储打开场景区块诊断",
    "Token 前10位": "前端诊断日志不能输出令牌片段",
    "console.info(`[trace]": "intent trace 不能直接输出到生产控制台",
    "console.warn(`[trace]": "intent trace 不能直接输出到生产控制台",
    "console.info('[noise-guard]": "浏览器扩展噪音处理不能直接输出到生产控制台",
    "'待办ID', '失败原因', '原因编码'": "我的工作台失败明细导出不能暴露原因编码列",
    "'错误分类', '建议动作', '错误消息', '追踪ID'": "我的工作台失败明细导出必须使用业务处理口径",
    "item.suggested_action || ''": "我的工作台失败明细导出必须展示产品化建议动作",
    "item.error_category || ''": "我的工作台失败明细导出必须展示产品化处理类型",
    "row.reason_code || ''}:": "批量失败明细不能直接暴露原因编码",
    "复制原因编码": "正式用户面不能暴露原因编码操作",
    "复制建议动作": "正式用户面不能暴露建议动作原文操作",
    "复制结构化错误详情": "正式用户面不能暴露结构化错误详情操作",
    "追踪 ID": "正式用户面必须使用处理编号口径",
    "治理追踪": "正式用户面必须使用处理编号口径",
    "建议动作追踪": "正式用户面必须使用建议动作记录口径",
    "用户 ID": "正式用户面必须使用用户编号口径",
    "菜单 ID": "正式用户面必须使用菜单编号口径",
    "操作 ID": "正式用户面必须使用操作编号口径",
    "记录 ID": "正式用户面必须使用记录编号口径",
    "错误码": "正式用户面必须使用错误状态口径",
    "项目ID": "正式用户面必须使用项目编号口径",
    "排序：ID": "正式用户面必须使用排序编号口径",
    "Demo账号": "正式用户面不能暴露 Demo 口径",
    "string: 'ID'": "默认字段标签必须使用编号口径",
    "建议动作类型": "正式用户面必须使用处理建议口径",
    "建议动作结果": "正式用户面必须使用处理建议口径",
    "建议动作时间": "正式用户面必须使用处理建议口径",
    "导出全部建议动作": "正式用户面必须使用处理建议口径",
    "建议动作记录已导出": "正式用户面必须使用处理建议口径",
    "建议动作记录导出失败": "正式用户面必须使用处理建议口径",
    "建议动作执行失败": "正式用户面必须使用处理建议口径",
    "已执行建议动作": "正式用户面必须使用处理建议口径",
    "导出成功动作": "正式用户面必须使用处理建议口径",
    "导出失败动作": "正式用户面必须使用处理建议口径",
    "导出动作类型": "正式用户面不能拼接处理建议协议类型",
    "未知错误": "正式用户面不能暴露未知错误口径",
    "未知渲染异常": "正式用户面不能暴露渲染异常口径",
    "场景注册异常": "正式用户面必须使用配置异常口径",
    "关键解析错误": "正式用户面必须使用配置解析问题口径",
    "解析错误（": "正式用户面必须使用配置解析问题口径",
    "暂无解析错误": "正式用户面必须使用配置解析问题口径",
    "V2 解析错误": "正式用户面不能暴露内部契约版本口径",
    "提交失败：记录尚未创建": "正式用户面必须给出可操作提交指引",
    "当前环境未返回完整首页契约": "首页兜底不能暴露契约实现",
    "最小可用视图": "首页兜底必须使用业务入口口径",
    "页面内容暂不可用": "页面模块兜底必须给出配置状态",
    "当前入口暂不可用": "入口兜底必须给出配置状态",
    "功能入口暂时不可用": "入口失败兜底必须给出可操作状态",
    "诊断页": "正式用户面必须使用工作台或运行详情口径",
    "仅用于排查": "正式用户面不能暴露排查口径",
    "动作类型": "正式用户面必须使用操作类型口径",
    "契约类型": "正式用户面必须使用配置类型口径",
    "契约链接": "正式用户面必须使用配置链接口径",
    "数据源协议": "正式用户面必须使用数据来源口径",
    "契约驱动": "正式用户面必须使用配置驱动口径",
    "契约已加载": "正式用户面必须使用配置口径",
    "契约可用": "正式用户面必须使用配置口径",
    "契约问题数": "正式用户面必须使用配置口径",
    "内部用户": "正式用户面必须使用协作用户口径",
    "内部入口": "正式用户面必须使用补充入口口径",
    "内部字段": "正式用户面必须使用系统字段口径",
    "解析异常": "正式用户面必须使用配置问题口径",
    "系统补充规则": "正式用户面必须使用系统补充配置口径",
    "无系统补充字段生效": "正式用户面必须使用系统补充配置口径",
    "capability_fallback: '系统补充'": "事项来源必须使用系统补充事项口径",
    "业务模型": "正式用户面必须使用业务对象口径",
    "契约模式": "正式用户面必须使用配置模式口径",
    "契约视图": "正式用户面必须使用配置视图口径",
    "契约筛选": "正式用户面必须使用配置筛选口径",
    "契约操作数": "正式用户面必须使用配置操作数口径",
    "契约分页数": "正式用户面必须使用配置分页数口径",
    "契约提醒数": "正式用户面必须使用配置提醒数口径",
    "契约降级": "正式用户面必须使用配置补充状态口径",
    "V2 暂存可用": "正式用户面不能暴露内部版本口径",
    "V2 组件数": "正式用户面不能暴露内部版本口径",
    "V2 操作数": "正式用户面不能暴露内部版本口径",
    "V2 按钮状态数": "正式用户面不能暴露内部版本口径",
    "V2 字段编码数": "正式用户面不能暴露内部版本口径",
    "V2 字段重叠数": "正式用户面不能暴露内部版本口径",
    "V2 缺失字段": "正式用户面不能暴露内部版本口径",
    "V2 布局来源": "正式用户面不能暴露内部版本口径",
    "V2 全局来源": "正式用户面不能暴露内部版本口径",
    "V2 上下文来源": "正式用户面不能暴露内部版本口径",
    "V2 状态字段数": "正式用户面不能暴露内部版本口径",
    "V2 值字段数": "正式用户面不能暴露内部版本口径",
    "V2 主数据字段数": "正式用户面不能暴露内部版本口径",
    "V2 只读值数": "正式用户面不能暴露内部版本口径",
    "V2 值来源": "正式用户面不能暴露内部版本口径",
    "抽取统计": "正式用户面必须使用数据统计口径",
    "灰度版": "正式用户面必须使用试运行版口径",
    "历史数据适配": "正式用户面必须使用历史数据兼容口径",
    "缺少关联模型配置": "正式用户面必须使用关联业务对象口径",
    "当前模型不支持": "正式用户面必须使用业务对象口径",
    "重试请求": "正式用户面必须使用重试内容口径",
    "导出重试配置": "正式用户面必须使用重试内容口径",
    "错误状态": "正式用户面必须使用处理状态口径",
    "页面渲染失败": "正式用户面必须使用页面打开失败口径",
    "列表页面渲染失败": "正式用户面必须使用页面打开失败口径",
    "表单页面渲染失败": "正式用户面必须使用页面打开失败口径",
    "开发配置": "正式用户面必须使用调试配置口径",
    "可渲染目标": "正式用户面必须使用可展示内容口径",
    "场景渲染目标": "正式用户面必须使用场景展示内容口径",
    "场景解析失败": "正式用户面必须使用场景打开失败口径",
    "复制契约": "正式用户面必须使用复制配置口径",
    "导出契约": "正式用户面必须使用导出配置口径",
    "页面契约": "正式用户面必须使用页面配置口径",
    "表单页面契约": "正式用户面必须使用表单页面配置口径",
    "原生菜单结构": "菜单配置不能暴露 Odoo 原生结构口径",
    "可执行调度配置": "正式用户面必须使用可执行配置口径",
    "低代码配置契约": "正式用户面必须使用低代码配置口径",
    "window.alert(err instanceof Error ? err.message : '附件打开失败')": "列表页附件错误必须使用页面内反馈",
    "confirm(toolbarUiLabel('batch_confirm_delete'": "列表批量删除必须使用产品化确认弹窗",
    "confirm('确认删除这条关联记录？')": "关联记录删除必须使用产品化确认弹窗",
    "window.confirm('确认导入场景能力包？')": "能力包导入必须使用产品化确认弹窗",
    "window.confirm('确认回滚并固定到稳定版？')": "场景治理回滚必须使用产品化确认弹窗",
    "window.confirm(`确认删除新增菜单": "菜单删除必须使用产品化确认弹窗",
    "window.confirm([\n    `确认恢复": "配置版本恢复必须使用产品化确认弹窗",
    "window.confirm(\n    `${pageText('confirm_batch_complete_prefix'": "我的工作台批量完成必须使用产品化确认弹窗",
    "window.prompt(`${action.label || '操作'}原因`)": "表单操作原因必须使用产品化输入弹窗",
    "window.prompt(relationUiLabel(descriptor, 'page_unavailable_prompt'))": "表单关联快速创建必须使用产品化输入弹窗",
    "return window.confirm(message)": "表单危险操作必须使用产品化确认弹窗",
    "window.prompt(`${label}${suffix}`": "表单动态参数必须使用页面内参数表单",
    "HUD: role_key": "首页验收信息不能暴露工程字段名",
    "HUD: internal_tiles": "首页验收信息不能暴露工程字段名",
    "HUD: orchestration_blocks": "首页验收信息不能暴露工程字段名",
    "scene_key={{": "首页入口验收信息不能暴露工程字段名",
    "capability_key={{": "首页入口验收信息不能暴露工程字段名",
    "兜底入口": "应用壳层 HUD 指标必须使用产品化入口口径",
    "auto=[": "应用壳层 HUD 治理摘要不能直接暴露工程原因编码",
    "return `mode=${mode}": "表单契约元信息不能暴露工程字段名",
    "view_type=${viewType}": "表单契约元信息不能暴露工程字段名",
    "profile=${renderProfile.value}": "表单契约元信息不能暴露工程字段名",
    "rights=${rights.value": "表单契约元信息不能暴露工程字段名",
    "legacy policy": "表单配置摘要必须使用产品化规则口径",
    "head.view_type is": "表单配置问题必须使用产品化中文描述",
    "view_type is": "表单配置问题必须使用产品化中文描述",
    "v2.pageInfo.viewType is": "表单配置问题必须使用产品化中文描述",
    "[MenuTree] Received nodes": "导航菜单不能保留临时调试日志",
    "[MenuTree] First node": "导航菜单不能保留临时调试日志",
    "console.info(`[toast]": "记录操作反馈必须显示在页面内，不能只写入控制台",
    "console.warn('[list-columns]": "列表列配置失败必须通过页面状态反馈，不能只写入控制台",
    "console.warn('[list-field-mutation]": "列表字段操作失败必须通过页面状态反馈，不能只写入控制台",
    "console.warn(message, payload)": "列表运行时警告不能直接暴露到生产控制台",
    "console.warn('[native-favorite]": "表单收藏失败必须通过页面反馈，不能只写入控制台",
    "console.info('[ContractFormPage] auxiliary form preload skipped": "表单辅助数据预加载兜底不能写入生产控制台",
    "console.info(`[scene-mutation]": "场景操作结果必须通过页面反馈，不能只写入控制台",
    "console.warn('[scene-view] scene-ready hydration failed": "场景兜底渲染不能写入生产控制台",
    "console.error('[ActionView] render failed": "列表渲染失败必须通过页面错误面板反馈，不能只写入控制台",
    "console.error('[ContractFormPage] render failed": "表单渲染失败必须通过页面错误面板反馈，不能只写入控制台",
    "结构：{{ health.schema_version": "场景健康页不能直接展示协议结构字段",
    "运行来源：</strong> {{ governanceSnapshot.runtime_source": "场景健康页不能直接展示运行来源字段",
    "runGovernance('export_contract')\">导出契约": "场景健康页治理导出操作必须使用产品化文案",
    "视图类型') }}：{{ contractViewType || '-'": "列表配置摘要必须展示产品化视图名称",
    "页面模式') }}：{{ vm.page.viewMode || '-'": "列表配置摘要必须展示产品化页面模式",
    "item.view_type || 'list' }}": "配置工作台个人设置记录必须展示产品化视图名称",
    "契约引用：</strong> {{ health.contract_ref": "场景健康页必须使用产品化配置版本口径",
}


def iter_files() -> list[Path]:
    files: list[Path] = []
    for directory in SCAN_DIRS:
        if not directory.is_dir():
            continue
        for path in directory.rglob("*"):
            if path.is_file() and path.suffix in SCAN_SUFFIXES:
                files.append(path)
    return sorted(set(files))


def main() -> int:
    errors: list[str] = []
    for path in iter_files():
        text = path.read_text(encoding="utf-8")
        for phrase, reason in FORBIDDEN_PHRASES.items():
            if phrase not in text:
                continue
            for line_no, line in enumerate(text.splitlines(), start=1):
                if phrase in line:
                    rel = path.relative_to(ROOT)
                    errors.append(f"{rel}:{line_no}: {reason}: {phrase}")

    if errors:
        print("[frontend_product_language_guard] FAIL")
        for error in errors:
            print(f"- {error}")
        return 1

    print(f"[frontend_product_language_guard] PASS files={len(iter_files())} phrases={len(FORBIDDEN_PHRASES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
