# -*- coding: utf-8 -*-
# pyright: reportUnusedExpression=false
{
    'name': 'Smart Construction Core',
    'version': '17.0.0.1',
    'summary': 'Core module for construction enterprise management (Architecture 2.0)',
    'author': 'Leedefend',
    'depends': [
        'project',
        'purchase',
        'stock',
        'account',
        'mail',
        'uom',
        'product',
        'web',
        'base_tier_validation',
        'base_tier_validation_server_action',
    ],
    'data': [
        # 基础数据
        'data/sequence.xml',
        'data/dictionary_demo.xml',
        'data/cost_demo.xml',
        'data/project_stage_data.xml',

        # 安全
        'security/sc_groups.xml',
        'security/sc_capability_groups.xml',
        'security/sc_role_groups.xml',
        'security/sc_model_records.xml',
        'security/ir.model.access.csv',
        'data/sc_test_users.xml',
        'data/material_plan_tier_actions.xml',
        'data/payment_request_tier_actions.xml',

        # 顶级菜单基础
        'views/menu_root.xml',

        # 视图
        'views/core/cost_domain_views.xml',
        'views/core/project_boq_import_views.xml',
        'views/core/project_task_from_boq_views.xml',
        'views/core/project_structure_views.xml',
        'actions/project_structure_actions.xml',
        'views/core/boq_views.xml',
        'wizard/material_plan_to_rfq_views.xml',
        'views/core/material_plan_views.xml',
        'actions/finance_actions.xml',
        'views/core/project_views.xml',
        'views/core/task_boq_views.xml',
        'views/support/work_breakdown_views.xml',
        'views/support/tender_views.xml',
        'views/support/document_views.xml',
        'views/projection/operating_metrics_views.xml',
        'views/projection/project_dashboard_kanban.xml',
        'views/core/contract_views.xml',
        'views/core/project_contract_views.xml',
        'views/core/contract_line_search.xml',
        'views/core/purchase_extend_views.xml',
        'views/support/account_extend_views.xml',
        'views/support/product_extend_views.xml',
        'views/core/project_project_financial_views.xml',
        'views/core/project_budget_views.xml',
        'views/support/payment_request_tier_review_views.xml',
        'views/menu_finance_center.xml',
        'views/support/tier_review_views.xml',
        'views/core/project_extend_boq_views.xml',
        'views/core/payment_request_views.xml',
        'views/core/settlement_views.xml',
        'views/projection/treasury_ledger_views.xml',
        'views/core/workflow_views.xml',
        'views/menu.xml',
        'views/support/dictionary_views.xml',
        'views/support/quota_import_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'smart_construction_core/static/src/js/project_quota_center.js',
            'smart_construction_core/static/src/xml/project_quota_center.xml',
            'smart_construction_core/static/src/scss/project_quota_center.scss',
        ],
    },
    'demo': [
        # 如需演示数据再启用
        # 'data/cost_domain_demo.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
