# -*- coding: utf-8 -*-
# pyright: reportUnusedExpression=false
{
    'name': 'Smart Construction Core',
    'version': '17.0.0.3',
    'summary': 'Core module for construction enterprise management (Architecture 2.0)',
    'author': 'Leedefend',
    'depends': [
        'project',
        'purchase',
        'stock',
        'account',
        'mail',
        'auth_signup',
        'uom',
        'product',
        'web',
        'base_tier_validation',
        'base_tier_validation_server_action',
    ],
    'data': [
        # 基础数据
        'data/sequence.xml',
        'data/project_stage_data.xml',
        'data/project_next_action_rules.xml',
        'data/project_stage_requirement_items.xml',
        'data/cron_signup_throttle_gc.xml',
        'data/sc_extension_params.xml',
        'data/sc_scene_seed.xml',

        # 安全
        'security/sc_groups.xml',
        'security/sc_capability_groups.xml',
        'security/sc_role_groups.xml',
        'security/sc_model_records.xml',
        'security/ir.model.access.csv',
        'security/sc_record_rules.xml',
        'views/res_groups_menu_views.xml',
        'data/material_plan_tier_actions.xml',
        'data/payment_request_tier_actions.xml',

        # 顶级菜单基础
        'actions/project_list_actions.xml',
        'views/menu_root.xml',

        # 视图
        'views/core/cost_domain_views.xml',
        'views/core/project_boq_import_views.xml',
        'views/core/project_task_from_boq_views.xml',
        'views/core/project_structure_views.xml',
        'actions/execution_structure_actions_base.xml',
        'views/core/execution_structure_views.xml',
        'actions/execution_structure_actions.xml',
        'actions/project_structure_actions.xml',
        'views/core/boq_views.xml',
        'views/core/project_lifecycle_kanban_views.xml',
        'wizard/material_plan_to_rfq_views.xml',
        'views/core/material_plan_views.xml',
        'actions/finance_actions.xml',
        'actions/project_actions.xml',
        'views/core/project_list_views.xml',
        'views/core/project_search_views.xml',
        'views/core/project_views.xml',
        'views/core/task_boq_views.xml',
        'views/support/task_sc_state_views.xml',
        'views/support/work_breakdown_views.xml',
        'views/support/tender_views.xml',
        'views/support/document_views.xml',
        'views/projection/operating_metrics_views.xml',
        'views/projection/project_dashboard_kanban.xml',
        'views/core/contract_views.xml',
        'views/core/contract_line_search.xml',
        'views/core/purchase_extend_views.xml',
        'views/support/account_extend_views.xml',
        'views/support/product_extend_views.xml',
        'views/core/project_project_financial_views.xml',
        'views/core/project_budget_views.xml',
        'views/support/payment_request_tier_review_views.xml',
        'views/menu_finance_center.xml',
        'views/support/tier_review_views.xml',
        'views/core/project_extend_boq_views.xml',
        'views/core/payment_ledger_views.xml',
        'views/core/payment_request_views.xml',
        'views/core/project_overview_views.xml',
        'actions/project_actions_views.xml',
        'views/core/settlement_views.xml',
        'views/projection/treasury_ledger_views.xml',
        'views/core/workflow_views.xml',
        'views/menu.xml',
        'views/project_workbench_action.xml',
        'views/support/dictionary_views.xml',
        'views/support/quota_import_views.xml',
        'views/support/project_stage_requirements_views.xml',
        'views/support/project_stage_requirement_item_views.xml',
        'views/support/scene_orchestration_views.xml',
        'views/web_login_views.xml',
        'views/login_templates.xml',
        'views/signup_templates.xml',
        # Patch 文件移到最后加载
        'security/action_groups_patch.xml',
        'security/menu_tech_hide_patch.xml',
        'actions/project_native_action_overrides.xml',
    ],
    'assets': {
        'web.assets_frontend_minimal': [
            'smart_construction_core/static/src/js/auth_favicon.js',
            'smart_construction_core/static/src/scss/sc_login.scss',
        ],
        'web.assets_frontend': [
            'smart_construction_core/static/src/js/auth_favicon.js',
            'smart_construction_core/static/src/scss/sc_login.scss',
        ],
        'web.assets_backend': [
            'smart_construction_core/static/src/scss/sc_theme.scss',
            'smart_construction_core/static/src/js/title_manager.js',
            'smart_construction_core/static/src/xml/title_manager.xml',
            'smart_construction_core/static/src/config/domain_nav_map.js',
            'smart_construction_core/static/src/config/role_entry_map.js',
            'smart_construction_core/static/src/js/sc_sidebar.js',
            'smart_construction_core/static/src/js/sc_company_switcher_sidebar.js',
            'smart_construction_core/static/src/js/sc_project_workbench.js',
            'smart_construction_core/static/src/js/sc_project_workbench_client_action.js',
            'smart_construction_core/static/src/xml/sc_sidebar.xml',
            'smart_construction_core/static/src/xml/sc_sidebar_header.xml',
            'smart_construction_core/static/src/xml/sc_project_workbench.xml',
            'smart_construction_core/static/src/scss/sc_sidebar.scss',
            'smart_construction_core/static/src/scss/sc_company_switcher.scss',
            'smart_construction_core/static/src/scss/sc_workbench.scss',
            'smart_construction_core/static/src/js/draft_autosave_ui_patch.js',
            'smart_construction_core/static/src/js/draft_autosave_patch.js',
            'smart_construction_core/static/src/js/form_status_indicator_patch.js',
            'smart_construction_core/static/src/xml/form_status_indicator_patch.xml',
            'smart_construction_core/static/src/scss/form_status_indicator.scss',
            'smart_construction_core/static/src/js/project_form_tab_jump.js',
            'smart_construction_core/static/src/js/project_quota_center.js',
            'smart_construction_core/static/src/xml/project_quota_center.xml',
            'smart_construction_core/static/src/scss/project_quota_center.scss',
            'smart_construction_core/static/src/js/insight/insight_service.js',
            'smart_construction_core/static/src/js/insight/insight_nav.js',
            'smart_construction_core/static/src/js/insight/insight_widget.js',
            'smart_construction_core/static/src/js/insight/insight_view_widget.js',
            'smart_construction_core/static/src/scss/insight_banner.scss',
            'smart_construction_core/static/src/js/next_actions/next_actions_widget.js',
            'smart_construction_core/static/src/js/next_actions/next_actions_view_widget.js',
            'smart_construction_core/static/src/js/stage_requirements/stage_requirements_widget.js',
            'smart_construction_core/static/src/js/stage_requirements/stage_requirements_view_widget.js',
            'smart_construction_core/static/src/scss/next_actions.scss',
            'smart_construction_core/static/src/scss/project_overview.scss',
        ],
        'web.assets_tests': [
            'smart_construction_core/static/tests/sc_sidebar_tests.js',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'demo': [
        # 'data/cost_domain_demo.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
