#!/usr/bin/env python3
"""Build replay payload for legacy material stock and budget facts."""

from __future__ import annotations

import csv
import json
import os
import subprocess
from decimal import Decimal, InvalidOperation
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
ARTIFACT_DIR = REPO_ROOT / "artifacts/migration"
OUTPUT_CSV = ARTIFACT_DIR / "fresh_db_legacy_material_stock_replay_payload_v1.csv"
OUTPUT_JSON = ARTIFACT_DIR / "fresh_db_legacy_material_stock_replay_adapter_result_v1.json"

SQL_CONTAINER = os.getenv("LEGACY_MSSQL_CONTAINER", "legacy-mssql-restore")
SQLCMD = os.getenv("LEGACY_SQLCMD", "/opt/mssql-tools18/bin/sqlcmd")
SQL_PASSWORD = os.getenv("LEGACY_MSSQL_SA_PASSWORD", "LegacyRestore!2026")
SQL_DATABASE = os.getenv("LEGACY_MSSQL_DATABASE", "LegacyDb")

FIELDS = [
    "legacy_record_id",
    "legacy_parent_id",
    "legacy_pid",
    "source_table",
    "source_dataset",
    "fact_type",
    "document_no",
    "document_state",
    "project_legacy_id",
    "project_name",
    "partner_legacy_id",
    "partner_name",
    "contract_legacy_id",
    "contract_no",
    "material_legacy_id",
    "material_code",
    "material_name",
    "material_spec",
    "material_uom",
    "work_part",
    "department_name",
    "document_date",
    "created_time",
    "creator_name",
    "creator_legacy_user_id",
    "qty",
    "unit_price",
    "amount_total",
    "amount_no_tax",
    "tax_amount",
    "tax_rate",
    "attachment_ref",
    "note",
    "active",
]


def text_sql(expr: str) -> str:
    return f"REPLACE(REPLACE(REPLACE(COALESCE(CONVERT(varchar(max), {expr}), ''), CHAR(9), ' '), CHAR(10), ' '), CHAR(13), ' ')"


def date_sql(expr: str) -> str:
    return f"COALESCE(CONVERT(varchar(23), {expr}, 121), '')"


def sqlcmd(sql: str) -> list[str]:
    return [
        "docker",
        "exec",
        SQL_CONTAINER,
        SQLCMD,
        "-b",
        "-S",
        "localhost",
        "-U",
        "sa",
        "-P",
        SQL_PASSWORD,
        "-C",
        "-d",
        SQL_DATABASE,
        "-W",
        "-s",
        "\t",
        "-h",
        "-1",
        "-Q",
        sql,
    ]


def select_clause(
    *,
    table: str,
    fact_type: str,
    id_expr: str,
    parent_expr: str,
    pid_expr: str,
    source_dataset: str,
    document_no: str,
    document_state: str,
    project_id: str,
    project_name: str,
    partner_id: str,
    partner_name: str,
    contract_id: str,
    contract_no: str,
    material_id: str,
    material_code: str,
    material_name: str,
    material_spec: str,
    material_uom: str,
    work_part: str,
    department: str,
    document_date: str,
    created_time: str,
    creator_name: str,
    creator_id: str,
    qty: str,
    unit_price: str,
    amount_total: str,
    amount_no_tax: str,
    tax_amount: str,
    tax_rate: str,
    attachment: str,
    note: str,
    active_expr: str,
    from_sql: str,
) -> str:
    return f"""
SELECT
  {text_sql(id_expr)} AS legacy_record_id,
  {text_sql(parent_expr)} AS legacy_parent_id,
  {text_sql(pid_expr)} AS legacy_pid,
  '{table}' AS source_table,
  {text_sql(source_dataset)} AS source_dataset,
  '{fact_type}' AS fact_type,
  {text_sql(document_no)} AS document_no,
  {text_sql(document_state)} AS document_state,
  {text_sql(project_id)} AS project_legacy_id,
  {text_sql(project_name)} AS project_name,
  {text_sql(partner_id)} AS partner_legacy_id,
  {text_sql(partner_name)} AS partner_name,
  {text_sql(contract_id)} AS contract_legacy_id,
  {text_sql(contract_no)} AS contract_no,
  {text_sql(material_id)} AS material_legacy_id,
  {text_sql(material_code)} AS material_code,
  {text_sql(material_name)} AS material_name,
  {text_sql(material_spec)} AS material_spec,
  {text_sql(material_uom)} AS material_uom,
  {text_sql(work_part)} AS work_part,
  {text_sql(department)} AS department_name,
  {date_sql(document_date)} AS document_date,
  {date_sql(created_time)} AS created_time,
  {text_sql(creator_name)} AS creator_name,
  {text_sql(creator_id)} AS creator_legacy_user_id,
  {text_sql(qty)} AS qty,
  {text_sql(unit_price)} AS unit_price,
  {text_sql(amount_total)} AS amount_total,
  {text_sql(amount_no_tax)} AS amount_no_tax,
  {text_sql(tax_amount)} AS tax_amount,
  {text_sql(tax_rate)} AS tax_rate,
  {text_sql(attachment)} AS attachment_ref,
  {text_sql(note)} AS note,
  CASE WHEN {active_expr} THEN '1' ELSE '0' END AS active
{from_sql}
"""


def payload_sql() -> str:
    parts = [
        select_clause(
            table="T_RK_RKD",
            fact_type="stock_in",
            id_expr="ID",
            parent_expr="''",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="RKDH",
            document_state="DJZT",
            project_id="XMID",
            project_name="COALESCE(NULLIF(f_ProjectName, ''), NULLIF(DRXMMC, ''), NULLIF(GLXMMC, ''))",
            partner_id="Supplier_ID",
            partner_name="SupplierName",
            contract_id="HT_ID",
            contract_no="HTBH",
            material_id="''",
            material_code="''",
            material_name="BT",
            material_spec="''",
            material_uom="''",
            work_part="COALESCE(NULLIF(SGBWMC_ZB, ''), NULLIF(SGBW, ''))",
            department="RKBM",
            document_date="COALESCE(DJRQ, LRRQ)",
            created_time="LRRQ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="RK_ZSL",
            unit_price="0",
            amount_total="RK_ZJE",
            amount_no_tax="RK_ZJE_NO",
            tax_amount="RK_ZSE",
            tax_rate="SLV",
            attachment="FJ",
            note="BZ",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.T_RK_RKD",
        ),
        select_clause(
            table="T_RK_RKDCB",
            fact_type="stock_in_line",
            id_expr="ID",
            parent_expr="ZBID",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="LYBH",
            document_state="DHSM",
            project_id="''",
            project_name="''",
            partner_id="''",
            partner_name="''",
            contract_id="HTCBID",
            contract_no="''",
            material_id="CLID",
            material_code="CLBH",
            material_name="CLMC",
            material_spec="GGXH",
            material_uom="DW",
            work_part="SGBW",
            department="NKKM",
            document_date="GXSJ",
            created_time="GXSJ",
            creator_name="GXR",
            creator_id="''",
            qty="SL",
            unit_price="DJ",
            amount_total="HJ",
            amount_no_tax="JE_NO",
            tax_amount="SE",
            tax_rate="SLV",
            attachment="''",
            note="BZ",
            active_expr="1 = 1",
            from_sql="FROM dbo.T_RK_RKDCB",
        ),
        select_clause(
            table="T_CK_CKD",
            fact_type="stock_out",
            id_expr="ID",
            parent_expr="''",
            pid_expr="''",
            source_dataset="SJBMC",
            document_no="CKDH",
            document_state="DJZT",
            project_id="XMID",
            project_name="XMMC",
            partner_id="COALESCE(NULLIF(LLDWID, ''), NULLIF(GYSID, ''), NULLIF(DBDWID, ''))",
            partner_name="COALESCE(NULLIF(LLDWMC, ''), NULLIF(GYSMC, ''), NULLIF(DBDWMC, ''))",
            contract_id="''",
            contract_no="XSHTBH",
            material_id="''",
            material_code="''",
            material_name="BT",
            material_spec="''",
            material_uom="''",
            work_part="SGBWMC",
            department="CKBM",
            document_date="COALESCE(DJRQ, LRRQ)",
            created_time="LRRQ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="CKJE_ZB",
            amount_no_tax="BHSJE",
            tax_amount="0",
            tax_rate="SLV",
            attachment="FJ",
            note="BZ",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.T_CK_CKD",
        ),
        select_clause(
            table="T_CK_CKDCB",
            fact_type="stock_out_line",
            id_expr="ID",
            parent_expr="ZBID",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="GLDJRQ",
            document_state="DHSM",
            project_id="''",
            project_name="''",
            partner_id="GYSID",
            partner_name="GYSMC",
            contract_id="''",
            contract_no="''",
            material_id="CLID",
            material_code="CLBH",
            material_name="CLMC",
            material_spec="GGXH",
            material_uom="DW",
            work_part="LLDW",
            department="SSFLBM",
            document_date="GXSJ",
            created_time="GXSJ",
            creator_name="GXR",
            creator_id="''",
            qty="SL",
            unit_price="CKDJ",
            amount_total="CKJE",
            amount_no_tax="JE_NO",
            tax_amount="SE",
            tax_rate="SLV",
            attachment="''",
            note="BZ",
            active_expr="1 = 1",
            from_sql="FROM dbo.T_CK_CKDCB",
        ),
        select_clause(
            table="A_SCBS_CLRKD",
            fact_type="scbs_stock_in",
            id_expr="Id",
            parent_expr="''",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="DJBH",
            document_state="DJZT",
            project_id="XMID",
            project_name="XMMC",
            partner_id="GYSID",
            partner_name="GYS",
            contract_id="''",
            contract_no="''",
            material_id="''",
            material_code="''",
            material_name="''",
            material_spec="''",
            material_uom="''",
            work_part="SGBW",
            department="''",
            document_date="COALESCE(DCRQ, LRSJ)",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="JE",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="FJ",
            note="''",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.A_SCBS_CLRKD",
        ),
        select_clause(
            table="YT_JGZS_SGLKYSZB_CB1",
            fact_type="material_budget_item",
            id_expr="ID",
            parent_expr="ZBID",
            pid_expr="Pid",
            source_dataset="SJBMC",
            document_no="XH",
            document_state="CONVERT(varchar(max), isShow)",
            project_id="XMID",
            project_name="XMMC",
            partner_id="''",
            partner_name="''",
            contract_id="T_HTGL_HTBG_CB_Id",
            contract_no="''",
            material_id="NKKMID",
            material_code="f_Tree_Code",
            material_name="XMMC",
            material_spec="GGXH",
            material_uom="DW",
            work_part="SGBW",
            department="QDKM",
            document_date="createTime",
            created_time="createTime",
            creator_name="cueateUser",
            creator_id="''",
            qty="SL",
            unit_price="DJ",
            amount_total="HJ",
            amount_no_tax="HJ_NO",
            tax_amount="SE",
            tax_rate="SLV",
            attachment="''",
            note="BZ",
            active_expr="ISNULL(flagdelete, 0) = 0",
            from_sql="FROM dbo.YT_JGZS_SGLKYSZB_CB1",
        ),
        select_clause(
            table="YT_JGZS_NKKMB",
            fact_type="material_budget_item",
            id_expr="ID",
            parent_expr="f_Tree_ParentId",
            pid_expr="Pid",
            source_dataset="SJBMC",
            document_no="XH",
            document_state="YCZT",
            project_id="f_Tree_XMID",
            project_name="XMMC",
            partner_id="''",
            partner_name="''",
            contract_id="''",
            contract_no="ZBBH",
            material_id="Guid",
            material_code="f_Tree_Code",
            material_name="f_Tree_XM",
            material_spec="f_Tree_GGXH",
            material_uom="f_Tree_DW",
            work_part="''",
            department="f_LXMC",
            document_date="createtime",
            created_time="createtime",
            creator_name="createuser",
            creator_id="LRRID",
            qty="COALESCE(SL, GCL)",
            unit_price="f_Tree_DJ",
            amount_total="COALESCE(SL, GCL) * COALESCE(f_Tree_DJ, 0)",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="''",
            note="BZ",
            active_expr="ISNULL(f_Tree_Del, 0) = 0",
            from_sql="FROM dbo.YT_JGZS_NKKMB",
        ),
        select_clause(
            table="YT_JGZS_NKJCGXB",
            fact_type="material_cost_relation",
            id_expr="Id",
            parent_expr="GLJCBID",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="NKCODE",
            document_state="LXMC",
            project_id="XMID",
            project_name="XMMC",
            partner_id="''",
            partner_name="''",
            contract_id="''",
            contract_no="''",
            material_id="COALESCE(NULLIF(CLSJGUID, ''), NULLIF(CLEJGUID, ''), NULLIF(NKKMID, ''))",
            material_code="COALESCE(NULLIF(CLSJCODE, ''), NULLIF(CLS5JCODE, ''), NULLIF(NKCODE, ''))",
            material_name="COALESCE(NULLIF(CLSJMC, ''), NULLIF(CLS5JMC, ''), NULLIF(NKXM, ''))",
            material_spec="CLSJGGXH",
            material_uom="COALESCE(NULLIF(CLSJDW, ''), NULLIF(CLS5JDW, ''))",
            work_part="''",
            department="LXMC",
            document_date="LRSJ",
            created_time="LRSJ",
            creator_name="''",
            creator_id="''",
            qty="0",
            unit_price="0",
            amount_total="0",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="''",
            note="''",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.YT_JGZS_NKJCGXB",
        ),
        select_clause(
            table="YT_JGZS_SGLKYSZB_QD_CB1",
            fact_type="material_budget_item",
            id_expr="Id",
            parent_expr="ZBID",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="XMBM",
            document_state="CONVERT(varchar(max), IsShow)",
            project_id="''",
            project_name="''",
            partner_id="''",
            partner_name="''",
            contract_id="DRGZID",
            contract_no="''",
            material_id="NKKMID",
            material_code="XMBM",
            material_name="XMMC",
            material_spec="XMTZMS",
            material_uom="DW",
            work_part="''",
            department="''",
            document_date="LRSJ",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="GCL",
            unit_price="ZHDJ",
            amount_total="HJ",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="''",
            note="''",
            active_expr="ISNULL(del, 0) = 0",
            from_sql="FROM dbo.YT_JGZS_SGLKYSZB_QD_CB1",
        ),
        select_clause(
            table="YT_JGZS_NKKMB_QD",
            fact_type="material_budget_item",
            id_expr="Id",
            parent_expr="ParentGuid",
            pid_expr="pid",
            source_dataset="''",
            document_no="XMBM",
            document_state="CONVERT(varchar(max), IsShow)",
            project_id="XMID",
            project_name="XMMC",
            partner_id="''",
            partner_name="''",
            contract_id="''",
            contract_no="''",
            material_id="Guid",
            material_code="XMBM",
            material_name="QDXMMC",
            material_spec="XMTZMS",
            material_uom="DW",
            work_part="''",
            department="''",
            document_date="LRSJ",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="0",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="''",
            note="''",
            active_expr="ISNULL(del, 0) = 0",
            from_sql="FROM dbo.YT_JGZS_NKKMB_QD",
        ),
        select_clause(
            table="ZYJX_ZY_T_WZJJF_SBZLD",
            fact_type="material_lease_contract",
            id_expr="Id",
            parent_expr="''",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="DJBH",
            document_state="DJZT",
            project_id="XMID",
            project_name="XMMC",
            partner_id="CZDWID",
            partner_name="CZDW",
            contract_id="ZLXMID",
            contract_no="ZLXMMC",
            material_id="ZLXMID",
            material_code="''",
            material_name="ZLXMMC",
            material_spec="''",
            material_uom="''",
            work_part="''",
            department="''",
            document_date="COALESCE(DJRQ, LRSJ)",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="ZJE",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="FJ",
            note="BZ",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.ZYJX_ZY_T_WZJJF_SBZLD",
        ),
        select_clause(
            table="ZYJX_ZY_T_WZJJF_SBHZD",
            fact_type="material_lease_settlement",
            id_expr="Id",
            parent_expr="''",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="DJBH",
            document_state="DJZT",
            project_id="XMID",
            project_name="XMMC",
            partner_id="CZDWID",
            partner_name="CZDW",
            contract_id="ZLXMID",
            contract_no="ZLXMMC",
            material_id="ZLXMID",
            material_code="''",
            material_name="ZLXMMC",
            material_spec="''",
            material_uom="''",
            work_part="''",
            department="''",
            document_date="COALESCE(DJRQ, LRSJ)",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="JSJE",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="FJ",
            note="BZ",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.ZYJX_ZY_T_WZJJF_SBHZD",
        ),
        select_clause(
            table="ZYJX_ZY_T_WZJJF_ZLHT",
            fact_type="material_lease_contract",
            id_expr="Id",
            parent_expr="''",
            pid_expr="pid",
            source_dataset="SJBMC",
            document_no="DJBH",
            document_state="DJZT",
            project_id="XMID",
            project_name="XMMC",
            partner_id="CZDWID",
            partner_name="CZDW",
            contract_id="ZLXMID",
            contract_no="ZLXMMC",
            material_id="ZLXMID",
            material_code="''",
            material_name="ZLXMMC",
            material_spec="''",
            material_uom="''",
            work_part="''",
            department="''",
            document_date="COALESCE(DJRQ, LRSJ)",
            created_time="LRSJ",
            creator_name="LRR",
            creator_id="LRRID",
            qty="0",
            unit_price="0",
            amount_total="ZJE",
            amount_no_tax="0",
            tax_amount="0",
            tax_rate="0",
            attachment="FJ",
            note="BZ",
            active_expr="ISNULL(DEL, 0) = 0",
            from_sql="FROM dbo.ZYJX_ZY_T_WZJJF_ZLHT",
        ),
    ]
    return "SET NOCOUNT ON;\n" + "\nUNION ALL\n".join(parts) + "\nORDER BY source_table, document_date, legacy_record_id;"


def write_csv_payload() -> int:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    with subprocess.Popen(sqlcmd(payload_sql()), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True) as proc:
        if proc.stdout is None:
            raise RuntimeError("sqlcmd stdout unavailable")
        with OUTPUT_CSV.open("w", encoding="utf-8-sig", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(FIELDS)
            for line in proc.stdout:
                stripped = line.strip()
                if not stripped or stripped.startswith("(") and stripped.endswith("rows affected)"):
                    continue
                parts = line.rstrip("\r\n").split("\t")
                if len(parts) != len(FIELDS):
                    raise RuntimeError({"unexpected_sqlcmd_row_shape": len(parts), "expected": len(FIELDS), "line": line[:500]})
                writer.writerow(parts)
                count += 1
        return_code = proc.wait()
    if return_code != 0:
        raise RuntimeError({"sqlcmd_failed": return_code})
    return count


def write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def csv_summary() -> dict[str, object]:
    qty_total = Decimal("0")
    amount_total = Decimal("0")
    active_rows = 0
    material_rows = 0
    source_counts: dict[str, int] = {}
    fact_type_counts: dict[str, int] = {}
    with OUTPUT_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            source_counts[row["source_table"]] = source_counts.get(row["source_table"], 0) + 1
            fact_type_counts[row["fact_type"]] = fact_type_counts.get(row["fact_type"], 0) + 1
            if row.get("active") == "1":
                active_rows += 1
            if row.get("material_name"):
                material_rows += 1
            try:
                qty_total += Decimal(row.get("qty") or "0")
            except InvalidOperation:
                pass
            try:
                amount_total += Decimal(row.get("amount_total") or "0")
            except InvalidOperation:
                pass
    return {
        "active_rows": active_rows,
        "material_rows": material_rows,
        "qty_sum": str(qty_total),
        "amount_total_sum": str(amount_total),
        "source_counts": source_counts,
        "fact_type_counts": fact_type_counts,
    }


def main() -> int:
    rows = write_csv_payload()
    summary = csv_summary()
    payload = {
        "status": "PASS",
        "mode": "fresh_db_legacy_material_stock_replay_adapter",
        "total_rows": rows,
        "active_rows": summary["active_rows"],
        "material_rows": summary["material_rows"],
        "qty_sum": summary["qty_sum"],
        "amount_total_sum": summary["amount_total_sum"],
        "source_counts": summary["source_counts"],
        "fact_type_counts": summary["fact_type_counts"],
        "payload_csv": str(OUTPUT_CSV),
        "decision": "legacy_material_stock_payload_ready",
    }
    write_json(OUTPUT_JSON, payload)
    print("FRESH_DB_LEGACY_MATERIAL_STOCK_REPLAY_ADAPTER=" + json.dumps(payload, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
