# -*- coding: utf-8 -*-
from odoo import fields, models


class ScLegacySalaryLine(models.Model):
    _name = "sc.legacy.salary.line"
    _description = "Legacy Salary Line Fact"
    _order = "salary_year desc, salary_month desc, legacy_line_id"

    legacy_line_id = fields.Char(required=True, index=True)
    legacy_header_id = fields.Char(index=True)
    legacy_pid = fields.Char(index=True)
    legacy_header_pid = fields.Char(index=True)
    source_dataset = fields.Char(index=True)
    document_no = fields.Char(index=True)
    document_state = fields.Char(index=True)
    salary_year = fields.Integer(index=True)
    salary_month = fields.Integer(index=True)
    period_key = fields.Char(index=True)
    title = fields.Char(index=True)
    project_legacy_id = fields.Char(index=True)
    project_name = fields.Char(index=True)
    project_id = fields.Many2one("project.project", index=True, ondelete="set null")
    scope_legacy_ids = fields.Text()
    scope_names = fields.Text()
    person_legacy_id = fields.Char(index=True)
    person_name = fields.Char(index=True)
    department_legacy_id = fields.Char(index=True)
    department_name = fields.Char(index=True)
    position_legacy_id = fields.Char(index=True)
    position_name = fields.Char(index=True)
    id_number = fields.Char(index=True)
    salary_base = fields.Float()
    cash_amount = fields.Float()
    social_security = fields.Float()
    housing_fund = fields.Float()
    individual_tax = fields.Float()
    welfare_standard = fields.Float()
    bonus = fields.Float()
    deduction = fields.Float()
    gross_amount = fields.Float()
    performance_salary = fields.Float()
    net_salary = fields.Float()
    calculation_base = fields.Float()
    overtime_amount = fields.Float()
    post_allowance = fields.Float()
    seniority_salary = fields.Float()
    service_salary = fields.Float()
    meal_allowance = fields.Float()
    subsidy = fields.Float()
    overtime_pay = fields.Float()
    late_absence_deduction = fields.Float()
    attendance_deduction = fields.Float()
    medical_insurance_base = fields.Float()
    medical_insurance_company = fields.Float()
    unemployment_insurance = fields.Float()
    social_security_individual_deduction = fields.Float()
    social_security_company_deduction = fields.Float()
    tax_deduction = fields.Float()
    union_fee = fields.Float()
    housing_fund_deduction = fields.Float()
    payer_unit = fields.Char(index=True)
    payment_people_count = fields.Integer()
    header_total_amount = fields.Float()
    header_payable_amount = fields.Float()
    header_people_count = fields.Integer()
    company_legacy_id = fields.Char(index=True)
    company_name = fields.Char(index=True)
    department_summary_legacy_id = fields.Char(index=True)
    department_summary = fields.Char(index=True)
    creator_legacy_user_id = fields.Char(index=True)
    creator_name = fields.Char(index=True)
    created_time = fields.Datetime(index=True)
    modifier_legacy_user_id = fields.Char(index=True)
    modifier_name = fields.Char(index=True)
    modified_time = fields.Datetime(index=True)
    attachment_ref = fields.Char()
    source_note = fields.Text()
    line_note = fields.Text()
    source_table = fields.Char(default="BGGL_XZ_GZ_CB", required=True, index=True)
    active = fields.Boolean(default=True, index=True)

    _sql_constraints = [
        ("legacy_salary_line_unique", "unique(legacy_line_id)", "Legacy salary line id must be unique."),
    ]
