# -*- coding: utf-8 -*-

from odoo import fields, models


class ProjectProject(models.Model):
    _inherit = "project.project"

    # Migration carriers used by replay scripts. Business-useful values are
    # labeled as product fields; source/provenance values stay as history facts.
    short_name = fields.Char(string="项目简称")
    project_environment = fields.Char(string="项目环境")
    legacy_project_id = fields.Char(string="历史项目ID", index=True)
    legacy_parent_id = fields.Char(string="历史父项目ID", index=True)
    legacy_project_code = fields.Char(string="历史项目编号", index=True)
    legacy_company_id = fields.Char(string="历史公司ID", index=True)
    legacy_company_name = fields.Char(string="公司名称")
    legacy_specialty_type_id = fields.Char(string="历史专业类型ID", index=True)
    specialty_type_name = fields.Char(string="专业类型")
    legacy_price_method = fields.Char(string="计价方式")
    legacy_contract_status = fields.Char(string="合同状态")
    legacy_is_complete_project = fields.Char(string="完整项目标识")
    business_nature = fields.Char(string="经营性质")
    legacy_tax_organization_id = fields.Char(string="历史纳税组织ID", index=True)
    legacy_tax_organization_name = fields.Char(string="纳税组织")
    legacy_account_name = fields.Char(string="账户名称")
    legacy_account_number = fields.Char(string="账号")
    legacy_account_bank = fields.Char(string="开户行")
    detail_address = fields.Text(string="项目详细地址")
    project_profile = fields.Text(string="项目简介")
    project_area = fields.Char(string="项目面积")
    legacy_cost = fields.Char(string="成本")
    legacy_manage_fee_ratio = fields.Char(string="管理费率")
    legacy_is_shared_base = fields.Char(string="共享库标识")
    legacy_sort = fields.Char(string="历史排序")
    legacy_note = fields.Text(string="备注")
    legacy_attachment_ref = fields.Char(string="历史附件引用")
    legacy_source_created_by = fields.Char(string="历史录入人")
    legacy_source_created_by_id = fields.Char(string="历史录入人ID", index=True)
    legacy_source_created_at = fields.Char(string="历史录入时间")
    legacy_source_updated_by = fields.Char(string="历史修改人")
    legacy_source_updated_by_id = fields.Char(string="历史修改人ID", index=True)
    legacy_source_updated_at = fields.Char(string="历史修改时间")
    legacy_deleted_flag = fields.Char(string="历史删除标识")
    legacy_owner_unit = fields.Char(string="业主单位名称")
    legacy_owner_contact = fields.Char(string="业主联系人姓名")
    legacy_owner_contact_phone = fields.Char(string="业主联系电话")
    legacy_supervision_unit = fields.Char(string="监理单位")
    legacy_supervisory_engineer = fields.Char(string="总监理工程师")
    legacy_supervision_phone = fields.Char(string="监理电话")
    legacy_contract_agreement = fields.Text(string="合同协议")
    legacy_project_file = fields.Text(string="项目文件")
    project_overview = fields.Text(string="项目概况")
    legacy_contracting_method = fields.Char(string="承包方式")
    legacy_project_nature = fields.Char(string="项目性质")
    legacy_is_material_library = fields.Char(string="材料库标识")
    legacy_external_contract_id = fields.Char(string="历史外部合同ID", index=True)
    other_system_id = fields.Char(string="其他系统ID", index=True)
    other_system_code = fields.Char(string="其他系统编号", index=True)
    legacy_tax_type = fields.Char(string="征收类型")
    legacy_stage_id = fields.Char(string="历史阶段ID", index=True)
    legacy_stage_name = fields.Char(string="历史阶段")
    legacy_region_id = fields.Char(string="历史地区ID", index=True)
    legacy_region_name = fields.Char(string="地区")
    legacy_state = fields.Char(string="历史状态")
    legacy_xqrgz = fields.Char(string="确认规则")
    legacy_xqrgzr = fields.Char(string="确认人")
    legacy_xqrgzrid = fields.Char(string="历史确认人ID", index=True)
    legacy_xqrgzxzrid = fields.Char(string="历史确认协作人ID", index=True)
    legacy_xqrgzxzr = fields.Char(string="确认协作人")
    legacy_project_manager_name = fields.Char(string="项目经理姓名")
    legacy_technical_responsibility_name = fields.Char(string="技术负责人")
