# -*- coding: utf-8 -*-

from odoo import fields, models


class ProjectProject(models.Model):
    _inherit = "project.project"

    # Legacy project carriers used by migration replay scripts.
    short_name = fields.Char()
    project_environment = fields.Char()
    legacy_project_id = fields.Char(index=True)
    legacy_parent_id = fields.Char(index=True)
    legacy_project_code = fields.Char(index=True)
    legacy_company_id = fields.Char(index=True)
    legacy_company_name = fields.Char()
    legacy_specialty_type_id = fields.Char(index=True)
    specialty_type_name = fields.Char()
    legacy_price_method = fields.Char()
    legacy_contract_status = fields.Char()
    legacy_is_complete_project = fields.Char()
    business_nature = fields.Char()
    legacy_tax_organization_id = fields.Char(index=True)
    legacy_tax_organization_name = fields.Char()
    legacy_account_name = fields.Char()
    legacy_account_number = fields.Char()
    legacy_account_bank = fields.Char()
    detail_address = fields.Text()
    project_profile = fields.Text()
    project_area = fields.Char()
    legacy_cost = fields.Char()
    legacy_manage_fee_ratio = fields.Char()
    legacy_is_shared_base = fields.Char()
    legacy_sort = fields.Char()
    legacy_note = fields.Text()
    legacy_attachment_ref = fields.Char()
    legacy_source_created_by = fields.Char(string="旧系统录入人")
    legacy_source_created_by_id = fields.Char(string="旧系统录入人ID", index=True)
    legacy_source_created_at = fields.Char(string="旧系统录入时间")
    legacy_source_updated_by = fields.Char(string="旧系统修改人")
    legacy_source_updated_by_id = fields.Char(string="旧系统修改人ID", index=True)
    legacy_source_updated_at = fields.Char(string="旧系统修改时间")
    legacy_deleted_flag = fields.Char()
    legacy_owner_unit = fields.Char()
    legacy_owner_contact = fields.Char()
    legacy_owner_contact_phone = fields.Char()
    legacy_supervision_unit = fields.Char()
    legacy_supervisory_engineer = fields.Char()
    legacy_supervision_phone = fields.Char()
    legacy_contract_agreement = fields.Text()
    legacy_project_file = fields.Text()
    project_overview = fields.Text()
    legacy_contracting_method = fields.Char()
    legacy_project_nature = fields.Char()
    legacy_is_material_library = fields.Char()
    legacy_external_contract_id = fields.Char(index=True)
    other_system_id = fields.Char(index=True)
    other_system_code = fields.Char(index=True)
    legacy_tax_type = fields.Char()
    legacy_stage_id = fields.Char(index=True)
    legacy_stage_name = fields.Char()
    legacy_region_id = fields.Char(index=True)
    legacy_region_name = fields.Char()
    legacy_state = fields.Char()
    legacy_xqrgz = fields.Char()
    legacy_xqrgzr = fields.Char()
    legacy_xqrgzrid = fields.Char(index=True)
    legacy_xqrgzxzrid = fields.Char(index=True)
    legacy_xqrgzxzr = fields.Char()
    legacy_project_manager_name = fields.Char()
    legacy_technical_responsibility_name = fields.Char()
