# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "login",
        "canonical_intent": "system.login",
        "intent_class": "system",
        "handler_class": "LoginHandler",
        "request_schema": "auth.login.v1",
        "response_contract": "auth.login.v1",
        "capability_code": "system.auth.login",
        "permission_mode": "anonymous",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["system", "auth"],
    },
    {
        "intent_name": "session.bootstrap",
        "canonical_intent": "system.session.bootstrap",
        "intent_class": "system",
        "handler_class": "SessionBootstrapHandler",
        "request_schema": "session.bootstrap.v1",
        "response_contract": "session.bootstrap.v1",
        "capability_code": "system.session.bootstrap",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["system", "session"],
    },
    {
        "intent_name": "system.init",
        "canonical_intent": "system.init",
        "intent_class": "system",
        "handler_class": "SystemInitHandler",
        "request_schema": "system.init.v1",
        "response_contract": "system.init.v1",
        "capability_code": "system.init",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["system", "init"],
    },
    {
        "intent_name": "ui.contract",
        "canonical_intent": "ui.contract",
        "intent_class": "ui",
        "handler_class": "UIContractHandler",
        "request_schema": "ui.contract.v1",
        "response_contract": "ui.contract.v1",
        "capability_code": "ui.contract.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "contract"],
    },
]
