# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "chatter.post",
        "canonical_intent": "ui.chatter.post",
        "intent_class": "ui",
        "handler_class": "ChatterPostHandler",
        "request_schema": "ui.chatter.post.v1",
        "response_contract": "ui.chatter.post.v1",
        "capability_code": "ui.chatter.post",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["ui", "chatter", "post"],
    },
    {
        "intent_name": "chatter.timeline",
        "canonical_intent": "ui.chatter.timeline",
        "intent_class": "ui",
        "handler_class": "ChatterTimelineHandler",
        "request_schema": "ui.chatter.timeline.v1",
        "response_contract": "ui.chatter.timeline.v1",
        "capability_code": "ui.chatter.timeline",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "chatter", "timeline"],
    },
    {
        "intent_name": "scene.catalog",
        "canonical_intent": "app.scene.catalog",
        "intent_class": "app",
        "handler_class": "SceneCatalogHandler",
        "request_schema": "app.scene.catalog.v1",
        "response_contract": "app.scene.catalog.v1",
        "capability_code": "app.scene.catalog",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "catalog"],
    },
    {
        "intent_name": "scene.detail",
        "canonical_intent": "app.scene.detail",
        "intent_class": "app",
        "handler_class": "SceneDetailHandler",
        "request_schema": "app.scene.detail.v1",
        "response_contract": "app.scene.detail.v1",
        "capability_code": "app.scene.detail",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "detail"],
    },
    {
        "intent_name": "scene.health",
        "canonical_intent": "app.scene.health",
        "intent_class": "app",
        "handler_class": "SceneHealthHandler",
        "request_schema": "app.scene.health.v1",
        "response_contract": "app.scene.health.v1",
        "capability_code": "app.scene.health",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "health"],
    },
    {
        "intent_name": "scene.packages.installed",
        "canonical_intent": "app.scene.packages.installed",
        "intent_class": "app",
        "handler_class": "ScenePackagesInstalledHandler",
        "request_schema": "app.scene.packages.installed.v1",
        "response_contract": "app.scene.packages.installed.v1",
        "capability_code": "app.scene.packages.installed",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "packages", "installed"],
    },
    {
        "intent_name": "scene.package.list",
        "canonical_intent": "app.scene.package.list",
        "intent_class": "app",
        "handler_class": "ScenePackageListHandler",
        "request_schema": "app.scene.package.list.v1",
        "response_contract": "app.scene.package.list.v1",
        "capability_code": "app.scene.package.list",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "package", "list"],
    },
    {
        "intent_name": "workspace.collections",
        "canonical_intent": "app.workspace.collections",
        "intent_class": "app",
        "handler_class": "WorkspaceCollectionsHandler",
        "request_schema": "app.workspace.collections.v1",
        "response_contract": "app.workspace.collections.v1",
        "capability_code": "app.workspace.collections",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["workspace", "collections"],
    },
]

