# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "scene.governance.export_contract",
        "canonical_intent": "app.scene.governance.export_contract",
        "intent_class": "app",
        "handler_class": "SceneGovernanceExportContractHandler",
        "request_schema": "app.scene.governance.export_contract.v1",
        "response_contract": "app.scene.governance.export_contract.v1",
        "capability_code": "app.scene.governance.export_contract",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "governance", "export-contract"],
    },
    {
        "intent_name": "scene.governance.pin_stable",
        "canonical_intent": "app.scene.governance.pin_stable",
        "intent_class": "app",
        "handler_class": "SceneGovernancePinStableHandler",
        "request_schema": "app.scene.governance.pin_stable.v1",
        "response_contract": "app.scene.governance.pin_stable.v1",
        "capability_code": "app.scene.governance.pin_stable",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["scene", "governance", "pin-stable"],
    },
    {
        "intent_name": "scene.governance.rollback",
        "canonical_intent": "app.scene.governance.rollback",
        "intent_class": "app",
        "handler_class": "SceneGovernanceRollbackHandler",
        "request_schema": "app.scene.governance.rollback.v1",
        "response_contract": "app.scene.governance.rollback.v1",
        "capability_code": "app.scene.governance.rollback",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["scene", "governance", "rollback"],
    },
    {
        "intent_name": "scene.governance.set_channel",
        "canonical_intent": "app.scene.governance.set_channel",
        "intent_class": "app",
        "handler_class": "SceneGovernanceSetChannelHandler",
        "request_schema": "app.scene.governance.set_channel.v1",
        "response_contract": "app.scene.governance.set_channel.v1",
        "capability_code": "app.scene.governance.set_channel",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["scene", "governance", "set-channel"],
    },
    {
        "intent_name": "scene.package.dry_run_import",
        "canonical_intent": "app.scene.package.dry_run_import",
        "intent_class": "app",
        "handler_class": "ScenePackageDryRunImportHandler",
        "request_schema": "app.scene.package.dry_run_import.v1",
        "response_contract": "app.scene.package.dry_run_import.v1",
        "capability_code": "app.scene.package.dry_run_import",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "package", "dry-run-import"],
    },
    {
        "intent_name": "scene.package.export",
        "canonical_intent": "app.scene.package.export",
        "intent_class": "app",
        "handler_class": "ScenePackageExportHandler",
        "request_schema": "app.scene.package.export.v1",
        "response_contract": "app.scene.package.export.v1",
        "capability_code": "app.scene.package.export",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["scene", "package", "export"],
    },
    {
        "intent_name": "scene.package.import",
        "canonical_intent": "app.scene.package.import",
        "intent_class": "app",
        "handler_class": "ScenePackageImportHandler",
        "request_schema": "app.scene.package.import.v1",
        "response_contract": "app.scene.package.import.v1",
        "capability_code": "app.scene.package.import",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["scene", "package", "import"],
    },
]

