# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "app.catalog",
        "canonical_intent": "app.catalog",
        "intent_class": "app",
        "handler_class": "AppCatalogHandler",
        "request_schema": "app.catalog.v1",
        "response_contract": "app.catalog.v1",
        "capability_code": "app.catalog.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["app", "catalog"],
    },
    {
        "intent_name": "app.nav",
        "canonical_intent": "app.nav",
        "intent_class": "app",
        "handler_class": "AppNavHandler",
        "request_schema": "app.nav.v1",
        "response_contract": "app.nav.v1",
        "capability_code": "app.nav.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["app", "navigation"],
    },
    {
        "intent_name": "app.open",
        "canonical_intent": "app.open",
        "intent_class": "app",
        "handler_class": "AppOpenHandler",
        "request_schema": "app.open.v1",
        "response_contract": "app.open.v1",
        "capability_code": "app.open.execute",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["app", "open"],
    },
    {
        "intent_name": "meta.describe_model",
        "canonical_intent": "meta.describe_model",
        "intent_class": "meta",
        "handler_class": "MetaDescribeHandler",
        "request_schema": "meta.describe_model.v1",
        "response_contract": "meta.describe_model.v1",
        "capability_code": "meta.describe_model.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["meta", "model"],
    },
    {
        "intent_name": "meta.intent_catalog",
        "canonical_intent": "meta.intent_catalog",
        "intent_class": "meta",
        "handler_class": "MetaIntentCatalogHandler",
        "request_schema": "meta.intent_catalog.v1",
        "response_contract": "meta.intent_catalog.v1",
        "capability_code": "meta.intent_catalog.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["meta", "intent"],
    },
    {
        "intent_name": "system.init.inspect",
        "canonical_intent": "system.init.inspect",
        "intent_class": "system",
        "handler_class": "SystemInitInspectHandler",
        "request_schema": "system.init.inspect.v1",
        "response_contract": "system.init.inspect.v1",
        "capability_code": "system.init.inspect",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["system", "init", "inspect"],
    },
    {
        "intent_name": "ui.contract.enhanced",
        "canonical_intent": "ui.contract.enhanced",
        "intent_class": "ui",
        "handler_class": "EnhancedUIContractHandler",
        "request_schema": "ui.contract.enhanced.v1",
        "response_contract": "ui.contract.enhanced.v1",
        "capability_code": "ui.contract.enhanced.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "contract", "enhanced"],
    },
    {
        "intent_name": "ui.contract.model.view",
        "canonical_intent": "ui.contract.model.view",
        "intent_class": "ui",
        "handler_class": "EnhancedModelViewHandler",
        "request_schema": "ui.contract.model.view.v1",
        "response_contract": "ui.contract.model.view.v1",
        "capability_code": "ui.contract.model.view.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "contract", "model-view"],
    },
]

