# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "api.data",
        "canonical_intent": "api.data",
        "intent_class": "api",
        "handler_class": "ApiDataHandler",
        "request_schema": "api.data.v1",
        "response_contract": "api.data.v1",
        "capability_code": "api.data.read",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["api", "data"],
    },
    {
        "intent_name": "api.data.batch",
        "canonical_intent": "api.data.batch",
        "intent_class": "api",
        "handler_class": "ApiDataBatchHandler",
        "request_schema": "api.data.batch.v1",
        "response_contract": "api.data.batch.v1",
        "capability_code": "api.data.batch",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["api", "data", "batch"],
    },
    {
        "intent_name": "api.data.create",
        "canonical_intent": "api.data.create",
        "intent_class": "api",
        "handler_class": "ApiDataWriteHandler",
        "request_schema": "api.data.create.v1",
        "response_contract": "api.data.create.v1",
        "capability_code": "api.data.create",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["api", "data", "create"],
    },
    {
        "intent_name": "api.data.unlink",
        "canonical_intent": "api.data.unlink",
        "intent_class": "api",
        "handler_class": "ApiDataUnlinkHandler",
        "request_schema": "api.data.unlink.v1",
        "response_contract": "api.data.unlink.v1",
        "capability_code": "api.data.unlink",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["api", "data", "unlink"],
    },
    {
        "intent_name": "api.onchange",
        "canonical_intent": "api.onchange",
        "intent_class": "api",
        "handler_class": "ApiOnchangeHandler",
        "request_schema": "api.onchange.v1",
        "response_contract": "api.onchange.v1",
        "capability_code": "api.onchange",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["api", "onchange"],
    },
    {
        "intent_name": "auth.logout",
        "canonical_intent": "system.auth.logout",
        "intent_class": "system",
        "handler_class": "LogoutHandler",
        "request_schema": "system.auth.logout.v1",
        "response_contract": "system.auth.logout.v1",
        "capability_code": "system.auth.logout",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["system", "auth", "logout"],
    },
    {
        "intent_name": "release.operator.approve",
        "canonical_intent": "domain.release.operator.approve",
        "intent_class": "domain",
        "handler_class": "ReleaseOperatorApproveHandler",
        "request_schema": "domain.release.operator.approve.v1",
        "response_contract": "domain.release.operator.approve.v1",
        "capability_code": "domain.release.operator.approve",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["domain", "release", "operator", "approve"],
    },
    {
        "intent_name": "release.operator.promote",
        "canonical_intent": "domain.release.operator.promote",
        "intent_class": "domain",
        "handler_class": "ReleaseOperatorPromoteHandler",
        "request_schema": "domain.release.operator.promote.v1",
        "response_contract": "domain.release.operator.promote.v1",
        "capability_code": "domain.release.operator.promote",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["domain", "release", "operator", "promote"],
    },
    {
        "intent_name": "release.operator.rollback",
        "canonical_intent": "domain.release.operator.rollback",
        "intent_class": "domain",
        "handler_class": "ReleaseOperatorRollbackHandler",
        "request_schema": "domain.release.operator.rollback.v1",
        "response_contract": "domain.release.operator.rollback.v1",
        "capability_code": "domain.release.operator.rollback",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["domain", "release", "operator", "rollback"],
    },
    {
        "intent_name": "release.operator.surface",
        "canonical_intent": "domain.release.operator.surface",
        "intent_class": "domain",
        "handler_class": "ReleaseOperatorSurfaceHandler",
        "request_schema": "domain.release.operator.surface.v1",
        "response_contract": "domain.release.operator.surface.v1",
        "capability_code": "domain.release.operator.surface",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["domain", "release", "operator", "surface"],
    },
    {
        "intent_name": "sample.enhanced",
        "canonical_intent": "app.sample.enhanced",
        "intent_class": "app",
        "handler_class": "EnhancedSampleHandler",
        "request_schema": "app.sample.enhanced.v1",
        "response_contract": "app.sample.enhanced.v1",
        "capability_code": "app.sample.enhanced",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["app", "sample", "enhanced"],
    },
]

