# -*- coding: utf-8 -*-

ENTRIES = [
    {
        "intent_name": "execute_button",
        "canonical_intent": "ui.execute_button",
        "intent_class": "ui",
        "handler_class": "ExecuteButtonHandler",
        "request_schema": "ui.execute_button.v1",
        "response_contract": "ui.execute_button.v1",
        "capability_code": "ui.execute.button",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["ui", "execute", "button"],
    },
    {
        "intent_name": "file.download",
        "canonical_intent": "ui.file.download",
        "intent_class": "ui",
        "handler_class": "FileDownloadHandler",
        "request_schema": "ui.file.download.v1",
        "response_contract": "ui.file.download.v1",
        "capability_code": "ui.file.download",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "file", "download"],
    },
    {
        "intent_name": "file.upload",
        "canonical_intent": "ui.file.upload",
        "intent_class": "ui",
        "handler_class": "FileUploadHandler",
        "request_schema": "ui.file.upload.v1",
        "response_contract": "ui.file.upload.v1",
        "capability_code": "ui.file.upload",
        "permission_mode": "authenticated",
        "idempotent": False,
        "version": "1.0.0",
        "tags": ["ui", "file", "upload"],
    },
    {
        "intent_name": "load_contract",
        "canonical_intent": "ui.load_contract",
        "intent_class": "ui",
        "handler_class": "LoadContractHandler",
        "request_schema": "ui.load_contract.v1",
        "response_contract": "ui.load_contract.v1",
        "capability_code": "ui.contract.load",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "contract", "load"],
    },
    {
        "intent_name": "load_metadata",
        "canonical_intent": "meta.load_metadata",
        "intent_class": "meta",
        "handler_class": "LoadMetadataHandler",
        "request_schema": "meta.load_metadata.v1",
        "response_contract": "meta.load_metadata.v1",
        "capability_code": "meta.load_metadata",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["meta", "load", "metadata"],
    },
    {
        "intent_name": "load_view",
        "canonical_intent": "ui.load_view",
        "intent_class": "ui",
        "handler_class": "LoadModelViewHandler",
        "request_schema": "ui.load_view.v1",
        "response_contract": "ui.load_view.v1",
        "capability_code": "ui.view.load",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "view", "load"],
    },
    {
        "intent_name": "permission.check",
        "canonical_intent": "system.permission.check",
        "intent_class": "system",
        "handler_class": "PermissionCheckHandler",
        "request_schema": "system.permission.check.v1",
        "response_contract": "system.permission.check.v1",
        "capability_code": "system.permission.check",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["system", "permission", "check"],
    },
    {
        "intent_name": "page.contract",
        "canonical_intent": "ui.page.contract",
        "intent_class": "ui",
        "handler_class": "PageContractHandler",
        "request_schema": "ui.page.contract.v1",
        "response_contract": "ui.page.contract.v1",
        "capability_code": "ui.page.contract",
        "permission_mode": "authenticated",
        "idempotent": True,
        "version": "1.0.0",
        "tags": ["ui", "page", "contract"],
    },
]

