# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Dict


def build_page_contracts(_data: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "schema_version": "v1",
        "pages": {
            "home": {"schema_version": "v1", "texts": {}},
            "login": {
                "schema_version": "v1",
                "texts": {
                    "title": "Login",
                    "username_label": "Username",
                    "password_label": "Password",
                    "submit_idle": "Sign in",
                    "submit_loading": "Signing in...",
                    "error_login_failed": "Login failed",
                },
            },
            "menu": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Resolving menu...",
                    "info_title": "Menu group",
                    "error_title": "Menu resolve failed",
                    "error_invalid_menu_id": "invalid menu id",
                    "error_resolve_failed": "resolve menu failed",
                },
            },
            "placeholder": {
                "schema_version": "v1",
                "texts": {
                    "title": "Dynamic View Placeholder",
                    "route_label": "Route",
                    "params_label": "Params",
                },
            },
            "workbench": {
                "schema_version": "v1",
                "texts": {
                    "header_title": "页面暂时无法打开",
                    "header_subtitle": "我们已为你保留可继续操作的入口。",
                    "action_go_workbench": "返回工作台",
                    "action_open_menu": "打开菜单",
                    "action_refresh": "刷新",
                    "panel_title": "页面暂时无法打开",
                    "message_nav_menu_no_action": "当前菜单是目录，暂时没有可进入的子菜单。",
                    "message_act_no_model": "当前动作对应的是自定义工作区，未绑定数据模型。",
                    "message_act_unsupported_type": "当前动作类型暂未在门户壳层支持。",
                    "message_contract_context_missing": "页面缺少契约必需上下文（例如 action_id）。",
                    "message_capability_missing": "当前账号尚未开通该能力。",
                    "message_default": "你可以返回工作台或打开菜单继续操作。",
                },
            },
            "my_work": {
                "schema_version": "v1",
                "texts": {
                    "title": "我的工作",
                    "loading_title": "加载我的工作中...",
                    "empty_desc": "状态良好。你可以返回工作台查看整体态势，或进入风险驾驶舱继续巡检。",
                    "error_request_failed": "请求失败",
                    "feedback_save_preset_failed": "保存常用筛选失败",
                    "feedback_apply_preset_failed": "应用常用筛选失败",
                    "feedback_clear_preset_failed": "清除常用筛选失败",
                },
            },
            "scene": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "正在加载场景...",
                    "error_fallback": "场景加载失败",
                    "forbidden_title": "能力未开通",
                    "forbidden_message": "当前角色无法进入该场景。",
                    "forbidden_title_permission": "权限不足",
                    "forbidden_message_scope_missing": "当前角色能力范围不包含该场景所需能力。",
                    "error_scene_target_unsupported": "scene target unsupported",
                    "error_scene_resolve_failed": "scene resolve failed",
                },
            },
            "action": {
                "schema_version": "v1",
                "texts": {
                    "status_loading": "加载中",
                    "status_error": "加载失败",
                    "status_empty": "暂无数据",
                    "status_ready": "已就绪",
                    "intent_title_risk": "风险驾驶舱：先处理严重与逾期风险",
                    "intent_summary_risk": "优先完成分派、关闭或发起审批，避免风险停留在“仅可见”状态。",
                    "intent_action_risk_todo": "待我处理风险",
                    "intent_action_risk_scene": "打开风险场景",
                    "empty_title_risk": "当前暂无风险记录",
                    "empty_hint_risk": "建议转到“我的工作”处理风险待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_risk": "处理风险待办",
                    "secondary_action_risk": "进入风险驾驶舱",
                    "intent_title_contract": "合同执行：优先识别付款与变更风险",
                    "intent_summary_contract": "先看执行率与付款状态，再进入异常合同处理。",
                    "intent_action_contract_todo": "处理合同待办",
                    "intent_action_contract_dashboard": "查看风险驾驶舱",
                    "empty_title_contract": "当前暂无合同记录",
                    "empty_hint_contract": "可前往“我的工作”查看合同待办，或进入风险驾驶舱追踪履约风险。",
                    "primary_action_contract": "处理合同待办",
                    "secondary_action_contract": "查看风险驾驶舱",
                    "intent_title_cost": "成本执行：先回答是否超支",
                    "intent_summary_cost": "优先关注超支金额与超支项，再下钻到具体偏差来源。",
                    "intent_action_cost_todo": "处理成本待办",
                    "intent_action_cost_dashboard": "查看风险驾驶舱",
                    "empty_title_cost": "当前暂无成本记录",
                    "empty_hint_cost": "可前往“我的工作”处理成本待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_cost": "处理超支待办",
                    "secondary_action_cost": "查看风险驾驶舱",
                    "intent_title_project": "项目视角：先判断是否可控",
                    "intent_summary_project": "优先查看风险、审批与经营指标，再决定下一步动作。",
                    "intent_action_project_todo": "查看项目待办",
                    "intent_action_project_dashboard": "进入风险驾驶舱",
                    "empty_title_project": "当前暂无项目记录",
                    "empty_hint_project": "建议进入“我的工作”处理项目待办，或去风险驾驶舱查看全局状态。",
                    "primary_action_project": "查看项目待办",
                    "secondary_action_project": "进入风险驾驶舱",
                    "intent_title_default": "业务列表：先看状态，再执行动作",
                    "intent_summary_default": "通过快速筛选与快捷操作，优先处理最关键事项。",
                    "intent_action_default_home": "工作台",
                    "intent_action_default_my_work": "我的工作",
                    "empty_title_default": "当前视图暂无数据",
                    "empty_hint_default": "建议切换到我的工作或风险驾驶舱继续处理。",
                    "primary_action_default": "去我的工作",
                    "secondary_action_default": "去风险驾驶舱",
                    "empty_reason_default": "可能因为暂无业务数据、当前角色权限受限，或数据尚未生成。",
                    "empty_reason_filter": "可能由当前筛选条件导致无数据，建议先清除筛选后重试。",
                    "empty_reason_wbs": "当前尚未生成执行结构数据，可先在项目立项或工程结构中创建后再查看。",
                },
            },
            "record": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Loading record...",
                    "saving_title": "Saving record...",
                    "error_fallback": "Record load failed",
                    "status_loading": "Loading",
                    "status_error": "Error",
                    "status_empty": "Empty",
                    "status_ready": "Ready",
                    "status_editing": "Editing",
                    "status_saving": "Saving",
                    "error_load_record": "failed to load record",
                    "error_execute_button": "failed to execute button",
                    "error_save_record": "failed to save record",
                    "chatter_load_failed": "Failed to load chatter",
                    "chatter_post_failed": "Failed to post chatter message",
                    "chatter_upload_failed": "Failed to upload file",
                    "chatter_download_failed": "Failed to download file",
                },
            },
            "scene_health": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Health Dashboard",
                    "subtitle": "可视化查看场景健康状态与自动降级结果。",
                    "loading_title": "Loading scene health...",
                    "error_fallback": "health request failed",
                    "error_reason_required": "reason is required for governance action",
                    "error_governance_failed": "governance action failed",
                },
            },
            "scene_packages": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Packages",
                    "subtitle": "导入、导出与审阅已安装的 Scene 能力包。",
                    "loading_title": "Loading packages...",
                    "error_title": "Package operation failed",
                    "error_load_failed": "load packages failed",
                    "error_dry_run_failed": "dry-run failed",
                    "error_import_failed": "import failed",
                    "error_export_failed": "export failed",
                    "error_reason_required": "reason is required for import",
                },
            },
            "usage_analytics": {
                "schema_version": "v1",
                "texts": {
                    "title": "Usage Analytics",
                    "loading_title": "Loading usage report...",
                    "error_fallback": "Failed to load usage report",
                    "empty_text": "暂无数据",
                    "error_export_failed": "导出失败",
                    "error_copy_export_params_failed": "复制导出参数失败",
                },
            },
        },
    }
