# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Dict


def build_page_contracts(_data: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "schema_version": "v1",
        "pages": {
            "home": {
                "schema_version": "v1",
                "texts": {
                    "title": "工作台",
                    "hero_lead": "围绕项目经营、风险与审批，优先处理今天最关键事项。",
                    "entry_error_title_prefix": "进入失败：",
                    "action_retry": "重试",
                    "action_acknowledge": "知道了",
                    "search_placeholder": "搜索功能名称或说明",
                    "search_clear": "清空搜索",
                    "ready_only_label": "仅显示可进入功能",
                    "state_all": "全部",
                    "state_ready": "可进入",
                    "state_locked": "暂不可用",
                    "state_preview": "即将开放",
                    "capability_state_all": "功能语义：全部",
                    "capability_state_allow": "可用",
                    "capability_state_readonly": "只读",
                    "capability_state_deny": "禁止",
                    "capability_state_pending": "待开放",
                    "capability_state_coming_soon": "建设中",
                    "filter_tip_ready_only": "已启用“仅显示可进入功能”，暂不可用与即将开放不会展示。",
                    "lock_reason_all": "锁定原因：全部",
                    "action_clear_all_filters": "清空全部筛选",
                    "action_expand_all_groups": "展开全部分组",
                    "action_collapse_all_groups": "折叠全部分组",
                    "action_clear_recent": "清空最近使用",
                    "empty_ready_only_no_result": "当前启用了“仅显示可进入功能”，暂时没有可进入功能。",
                    "empty_search_no_result_prefix": "未找到与“",
                    "empty_search_no_result_suffix": "”相关的功能，请调整筛选条件。",
                    "empty_filter_no_result": "未找到相关功能，请调整筛选条件。",
                    "action_clear_lock_reason": "清除锁定原因",
                    "action_show_all_capabilities": "显示全部功能",
                    "action_clear_search_filters": "清空搜索与筛选",
                    "empty_no_capability": "当前账号暂无可用功能，可能因为角色权限未开通或工作台尚未配置。",
                    "action_switch_role": "切换角色",
                    "action_back_home": "返回首页",
                    "action_expand_help": "查看帮助",
                    "action_collapse_help": "收起帮助",
                    "empty_help_detail": "建议先点击“切换角色”确认当前角色；若仍无功能，请联系管理员开通角色权限或配置工作台目录。",
                    "entry_subtitle_empty": "无说明",
                    "role_fallback_owner": "负责人",
                    "role_label_executive": "高管",
                    "role_label_owner": "负责人",
                    "role_landing_fallback": "工作台首页",
                    "tile_title_fallback_prefix": "功能 ",
                    "scene_title_uncategorized": "未分类模块",
                    "scene_title_uncategorized_with_key_prefix": "未分类模块（",
                    "scene_title_uncategorized_with_key_suffix": ")",
                    "metric_title_fallback_prefix": "指标 ",
                    "todo_title_fallback_prefix": "待办 ",
                    "todo_desc_fallback": "点击进入处理",
                    "risk_summary_fallback": "当前未出现严重风险，建议保持日常巡检节奏。",
                    "risk_action_title_fallback_prefix": "风险事项 ",
                    "risk_source_label_fallback_prefix": "来源 ",
                    "advice_title_fallback_prefix": "建议 ",
                    "level_red": "严重",
                    "level_amber": "关注",
                    "level_green": "正常",
                    "result_summary_prefix": "当前显示 ",
                    "result_summary_middle": " / ",
                    "result_summary_suffix": " 项功能",
                    "result_summary_state_prefix": "状态：",
                    "result_summary_capability_state_prefix": "功能语义：",
                    "result_summary_reason_prefix": "原因：",
                    "chip_search_prefix": "搜索：",
                    "chip_ready_only": "仅显示可进入",
                    "chip_state_prefix": "状态：",
                    "chip_capability_state_prefix": "功能语义：",
                    "chip_reason_prefix": "锁定原因：",
                    "scene_summary_prefix": "覆盖场景：",
                    "scene_summary_more": "…",
                    "recent_group_title": "最近使用",
                    "lock_reason_permission_denied": "权限不足",
                    "lock_reason_feature_disabled": "订阅未开通",
                    "lock_reason_role_scope_mismatch": "角色范围不匹配",
                    "lock_reason_scope_missing": "缺少前置条件",
                    "lock_reason_scope_cycle": "功能依赖异常",
                    "lock_reason_coming_soon": "功能建设中",
                    "lock_reason_waiting_open": "待审批开放",
                    "lock_reason_default": "当前不可用",
                    "action_enter_disabled": "暂不可用",
                    "action_enter_preview": "即将开放",
                    "action_enter_readonly": "只读进入",
                    "action_enter_default": "进入处理",
                    "enter_error_message_fallback": "功能入口暂时不可用",
                    "enter_error_hint_permission_denied": "请联系管理员开通对应权限后重试。",
                    "enter_error_hint_route_not_found": "入口配置异常，请稍后重试或联系管理员。",
                    "enter_error_hint_timeout": "网络连接超时，请检查网络后点击重试。",
                    "enter_error_hint_default": "请稍后重试；如果问题持续，请联系管理员。",
                },
            },
            "login": {
                "schema_version": "v1",
                "texts": {
                    "title": "Login",
                    "username_label": "Username",
                    "password_label": "Password",
                    "submit_idle": "Sign in",
                    "submit_loading": "Signing in...",
                    "error_login_failed": "Login failed",
                },
            },
            "menu": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Resolving menu...",
                    "info_title": "Menu group",
                    "error_title": "Menu resolve failed",
                    "error_invalid_menu_id": "invalid menu id",
                    "error_resolve_failed": "resolve menu failed",
                },
            },
            "placeholder": {
                "schema_version": "v1",
                "texts": {
                    "title": "Dynamic View Placeholder",
                    "route_label": "Route",
                    "params_label": "Params",
                },
            },
            "workbench": {
                "schema_version": "v1",
                "texts": {
                    "header_title": "页面暂时无法打开",
                    "header_subtitle": "我们已为你保留可继续操作的入口。",
                    "action_go_workbench": "返回工作台",
                    "action_open_menu": "打开菜单",
                    "action_refresh": "刷新",
                    "panel_title": "页面暂时无法打开",
                    "message_nav_menu_no_action": "当前菜单是目录，暂时没有可进入的子菜单。",
                    "message_act_no_model": "当前动作对应的是自定义工作区，未绑定数据模型。",
                    "message_act_unsupported_type": "当前动作类型暂未在门户壳层支持。",
                    "message_contract_context_missing": "页面缺少契约必需上下文（例如 action_id）。",
                    "message_capability_missing": "当前账号尚未开通该能力。",
                    "message_default": "你可以返回工作台或打开菜单继续操作。",
                },
            },
            "my_work": {
                "schema_version": "v1",
                "texts": {
                    "title": "我的工作",
                    "loading_title": "加载我的工作中...",
                    "empty_desc": "状态良好。你可以返回工作台查看整体态势，或进入风险驾驶舱继续巡检。",
                    "error_request_failed": "请求失败",
                    "feedback_save_preset_failed": "保存常用筛选失败",
                    "feedback_apply_preset_failed": "应用常用筛选失败",
                    "feedback_clear_preset_failed": "清除常用筛选失败",
                },
            },
            "scene": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "正在加载场景...",
                    "error_fallback": "场景加载失败",
                    "forbidden_title": "能力未开通",
                    "forbidden_message": "当前角色无法进入该场景。",
                    "forbidden_title_permission": "权限不足",
                    "forbidden_message_scope_missing": "当前角色能力范围不包含该场景所需能力。",
                    "error_scene_target_unsupported": "scene target unsupported",
                    "error_scene_resolve_failed": "scene resolve failed",
                },
            },
            "action": {
                "schema_version": "v1",
                "texts": {
                    "status_loading": "加载中",
                    "status_error": "加载失败",
                    "status_empty": "暂无数据",
                    "status_ready": "已就绪",
                    "intent_title_risk": "风险驾驶舱：先处理严重与逾期风险",
                    "intent_summary_risk": "优先完成分派、关闭或发起审批，避免风险停留在“仅可见”状态。",
                    "intent_action_risk_todo": "待我处理风险",
                    "intent_action_risk_scene": "打开风险场景",
                    "empty_title_risk": "当前暂无风险记录",
                    "empty_hint_risk": "建议转到“我的工作”处理风险待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_risk": "处理风险待办",
                    "secondary_action_risk": "进入风险驾驶舱",
                    "intent_title_contract": "合同执行：优先识别付款与变更风险",
                    "intent_summary_contract": "先看执行率与付款状态，再进入异常合同处理。",
                    "intent_action_contract_todo": "处理合同待办",
                    "intent_action_contract_dashboard": "查看风险驾驶舱",
                    "empty_title_contract": "当前暂无合同记录",
                    "empty_hint_contract": "可前往“我的工作”查看合同待办，或进入风险驾驶舱追踪履约风险。",
                    "primary_action_contract": "处理合同待办",
                    "secondary_action_contract": "查看风险驾驶舱",
                    "intent_title_cost": "成本执行：先回答是否超支",
                    "intent_summary_cost": "优先关注超支金额与超支项，再下钻到具体偏差来源。",
                    "intent_action_cost_todo": "处理成本待办",
                    "intent_action_cost_dashboard": "查看风险驾驶舱",
                    "empty_title_cost": "当前暂无成本记录",
                    "empty_hint_cost": "可前往“我的工作”处理成本待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_cost": "处理超支待办",
                    "secondary_action_cost": "查看风险驾驶舱",
                    "intent_title_project": "项目视角：先判断是否可控",
                    "intent_summary_project": "优先查看风险、审批与经营指标，再决定下一步动作。",
                    "intent_action_project_todo": "查看项目待办",
                    "intent_action_project_dashboard": "进入风险驾驶舱",
                    "empty_title_project": "当前暂无项目记录",
                    "empty_hint_project": "建议进入“我的工作”处理项目待办，或去风险驾驶舱查看全局状态。",
                    "primary_action_project": "查看项目待办",
                    "secondary_action_project": "进入风险驾驶舱",
                    "intent_title_default": "业务列表：先看状态，再执行动作",
                    "intent_summary_default": "通过快速筛选与快捷操作，优先处理最关键事项。",
                    "intent_action_default_home": "工作台",
                    "intent_action_default_my_work": "我的工作",
                    "empty_title_default": "当前视图暂无数据",
                    "empty_hint_default": "建议切换到我的工作或风险驾驶舱继续处理。",
                    "primary_action_default": "去我的工作",
                    "secondary_action_default": "去风险驾驶舱",
                    "empty_reason_default": "可能因为暂无业务数据、当前角色权限受限，或数据尚未生成。",
                    "empty_reason_filter": "可能由当前筛选条件导致无数据，建议先清除筛选后重试。",
                    "empty_reason_wbs": "当前尚未生成执行结构数据，可先在项目立项或工程结构中创建后再查看。",
                },
            },
            "record": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Loading record...",
                    "saving_title": "Saving record...",
                    "error_fallback": "Record load failed",
                    "status_loading": "Loading",
                    "status_error": "Error",
                    "status_empty": "Empty",
                    "status_ready": "Ready",
                    "status_editing": "Editing",
                    "status_saving": "Saving",
                    "error_load_record": "failed to load record",
                    "error_execute_button": "failed to execute button",
                    "error_save_record": "failed to save record",
                    "chatter_load_failed": "Failed to load chatter",
                    "chatter_post_failed": "Failed to post chatter message",
                    "chatter_upload_failed": "Failed to upload file",
                    "chatter_download_failed": "Failed to download file",
                    "view_node_unsupported_title": "View node unsupported",
                    "view_node_unsupported_message": "Layout nodes are present but renderer support is incomplete.",
                    "banner_saved": "Saved. Changes have been applied.",
                    "summary_status_stage": "项目状态与阶段",
                    "summary_risk": "关键风险摘要",
                    "summary_finance": "资金/产值指标",
                    "next_actions_title": "下一步动作",
                    "next_action_todo": "查看待办",
                    "next_action_risk": "查看风险",
                    "next_action_contract": "查看合同",
                    "next_action_cost": "查看成本",
                    "fallback_details_title": "项目详情",
                    "chatter_title": "协作时间线",
                    "chatter_input_placeholder": "输入评论，支持 @同事 ...",
                    "chatter_posting": "发布中...",
                    "chatter_post_action": "发布评论",
                    "chatter_uploading": "上传中…",
                    "chatter_empty": "暂无协作记录。",
                    "project_phase_unset": "未配置阶段",
                    "project_risk_ok": "正常，暂无高风险告警",
                    "project_risk_critical_prefix": "严重，当前高风险 ",
                    "project_risk_critical_suffix": " 项，需优先闭环",
                    "project_risk_attention_prefix": "关注，当前风险 ",
                    "project_risk_attention_suffix": " 项",
                    "project_output_prefix": "产值 ",
                    "project_output_unset": "产值未配置",
                    "project_pay_prefix": "付款比 ",
                    "project_pay_suffix": "%",
                    "project_pay_unset": "付款比未配置",
                    "readonly_hint_license_prefix": "当前为只读模式（License: ",
                    "readonly_hint_license_bundle_sep": ", Bundle: ",
                    "readonly_hint_license_suffix": "）。如需编辑权限请联系管理员。",
                    "readonly_hint_default": "当前记录处于只读模式，请联系管理员开通写权限。",
                    "missing_capability_prefix": "缺少能力：",
                    "missing_capability_sep": "、",
                    "missing_capability_license_prefix": "；当前 License: ",
                    "action_feedback_failed": "操作失败",
                },
            },
            "scene_health": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Health Dashboard",
                    "subtitle": "可视化查看场景健康状态与自动降级结果。",
                    "loading_title": "Loading scene health...",
                    "error_fallback": "health request failed",
                    "error_reason_required": "reason is required for governance action",
                    "error_governance_failed": "governance action failed",
                },
            },
            "scene_packages": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Packages",
                    "subtitle": "导入、导出与审阅已安装的 Scene 能力包。",
                    "loading_title": "Loading packages...",
                    "error_title": "Package operation failed",
                    "error_load_failed": "load packages failed",
                    "error_dry_run_failed": "dry-run failed",
                    "error_import_failed": "import failed",
                    "error_export_failed": "export failed",
                    "error_reason_required": "reason is required for import",
                },
            },
            "usage_analytics": {
                "schema_version": "v1",
                "texts": {
                    "title": "Usage Analytics",
                    "loading_title": "Loading usage report...",
                    "error_fallback": "Failed to load usage report",
                    "empty_text": "暂无数据",
                    "error_export_failed": "导出失败",
                    "error_copy_export_params_failed": "复制导出参数失败",
                },
            },
        },
    }
