# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Dict


def build_page_contracts(_data: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "schema_version": "v1",
        "pages": {
            "home": {
                "schema_version": "v1",
                "texts": {
                    "title": "工作台",
                    "hero_lead": "围绕项目经营、风险与审批，优先处理今天最关键事项。",
                    "entry_error_title_prefix": "进入失败：",
                    "action_retry": "重试",
                    "action_acknowledge": "知道了",
                    "search_placeholder": "搜索功能名称或说明",
                    "search_clear": "清空搜索",
                    "ready_only_label": "仅显示可进入功能",
                    "state_all": "全部",
                    "state_ready": "可进入",
                    "state_locked": "暂不可用",
                    "state_preview": "即将开放",
                    "capability_state_all": "功能语义：全部",
                    "capability_state_allow": "可用",
                    "capability_state_readonly": "只读",
                    "capability_state_deny": "禁止",
                    "capability_state_pending": "待开放",
                    "capability_state_coming_soon": "建设中",
                    "filter_tip_ready_only": "已启用“仅显示可进入功能”，暂不可用与即将开放不会展示。",
                    "lock_reason_all": "锁定原因：全部",
                    "action_clear_all_filters": "清空全部筛选",
                    "action_expand_all_groups": "展开全部分组",
                    "action_collapse_all_groups": "折叠全部分组",
                    "action_clear_recent": "清空最近使用",
                    "empty_ready_only_no_result": "当前启用了“仅显示可进入功能”，暂时没有可进入功能。",
                    "empty_search_no_result_prefix": "未找到与“",
                    "empty_search_no_result_suffix": "”相关的功能，请调整筛选条件。",
                    "empty_filter_no_result": "未找到相关功能，请调整筛选条件。",
                    "action_clear_lock_reason": "清除锁定原因",
                    "action_show_all_capabilities": "显示全部功能",
                    "action_clear_search_filters": "清空搜索与筛选",
                    "empty_no_capability": "当前账号暂无可用功能，可能因为角色权限未开通或工作台尚未配置。",
                    "action_switch_role": "切换角色",
                    "action_back_home": "返回首页",
                    "action_expand_help": "查看帮助",
                    "action_collapse_help": "收起帮助",
                    "empty_help_detail": "建议先点击“切换角色”确认当前角色；若仍无功能，请联系管理员开通角色权限或配置工作台目录。",
                    "entry_subtitle_empty": "无说明",
                    "role_fallback_owner": "负责人",
                    "role_label_executive": "高管",
                    "role_label_owner": "负责人",
                    "role_landing_fallback": "工作台首页",
                    "tile_title_fallback_prefix": "功能 ",
                    "scene_title_uncategorized": "未分类模块",
                    "scene_title_uncategorized_with_key_prefix": "未分类模块（",
                    "scene_title_uncategorized_with_key_suffix": ")",
                    "metric_title_fallback_prefix": "指标 ",
                    "todo_title_fallback_prefix": "待办 ",
                    "todo_desc_fallback": "点击进入处理",
                    "risk_summary_fallback": "当前未出现严重风险，建议保持日常巡检节奏。",
                    "risk_action_title_fallback_prefix": "风险事项 ",
                    "risk_source_label_fallback_prefix": "来源 ",
                    "advice_title_fallback_prefix": "建议 ",
                    "risk_trend_label_prefix": "T-",
                    "level_red": "严重",
                    "level_amber": "关注",
                    "level_green": "正常",
                    "trend_up_prefix": "↑ ",
                    "trend_down_prefix": "↓ ",
                    "trend_flat": "→ 0%",
                    "todo_label_approval": "审核付款申请",
                    "todo_label_contract": "查看合同异常",
                    "todo_label_risk": "处理风险事项",
                    "todo_label_change": "确认变更事项",
                    "todo_label_overdue": "处理逾期任务",
                    "todo_label_default": "查看详情",
                    "result_summary_prefix": "当前显示 ",
                    "result_summary_middle": " / ",
                    "result_summary_suffix": " 项功能",
                    "result_summary_state_prefix": "状态：",
                    "result_summary_capability_state_prefix": "功能语义：",
                    "result_summary_reason_prefix": "原因：",
                    "chip_search_prefix": "搜索：",
                    "chip_ready_only": "仅显示可进入",
                    "chip_state_prefix": "状态：",
                    "chip_capability_state_prefix": "功能语义：",
                    "chip_reason_prefix": "锁定原因：",
                    "scene_summary_prefix": "覆盖场景：",
                    "scene_summary_more": "…",
                    "recent_group_title": "最近使用",
                    "lock_reason_permission_denied": "权限不足",
                    "lock_reason_feature_disabled": "订阅未开通",
                    "lock_reason_role_scope_mismatch": "角色范围不匹配",
                    "lock_reason_scope_missing": "缺少前置条件",
                    "lock_reason_scope_cycle": "功能依赖异常",
                    "lock_reason_coming_soon": "功能建设中",
                    "lock_reason_waiting_open": "待审批开放",
                    "lock_reason_default": "当前不可用",
                    "action_enter_disabled": "暂不可用",
                    "action_enter_preview": "即将开放",
                    "action_enter_readonly": "只读进入",
                    "action_enter_approval": "审核付款申请",
                    "action_enter_contract": "查看合同异常",
                    "action_enter_risk": "处理风险事项",
                    "action_enter_change": "确认变更事项",
                    "action_enter_task": "处理任务",
                    "action_enter_default": "进入处理",
                    "enter_error_message_fallback": "功能入口暂时不可用",
                    "enter_error_hint_permission_denied": "请联系管理员开通对应权限后重试。",
                    "enter_error_hint_route_not_found": "入口配置异常，请稍后重试或联系管理员。",
                    "enter_error_hint_timeout": "网络连接超时，请检查网络后点击重试。",
                    "enter_error_hint_default": "请稍后重试；如果问题持续，请联系管理员。",
                },
            },
            "login": {
                "schema_version": "v1",
                "texts": {
                    "title": "Login",
                    "username_label": "Username",
                    "password_label": "Password",
                    "submit_idle": "Sign in",
                    "submit_loading": "Signing in...",
                    "error_login_failed": "Login failed",
                },
            },
            "menu": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Resolving menu...",
                    "info_title": "Menu group",
                    "error_title": "Menu resolve failed",
                    "error_invalid_menu_id": "invalid menu id",
                    "error_resolve_failed": "resolve menu failed",
                },
            },
            "placeholder": {
                "schema_version": "v1",
                "texts": {
                    "title": "Dynamic View Placeholder",
                    "route_label": "Route",
                    "params_label": "Params",
                },
            },
            "workbench": {
                "schema_version": "v1",
                "texts": {
                    "header_title": "页面暂时无法打开",
                    "header_subtitle": "我们已为你保留可继续操作的入口。",
                    "diagnostic_hint": "诊断页仅用于排查，不作为正式产品界面。",
                    "context_prefix": "推荐上下文：",
                    "action_clear_context": "清除",
                    "action_go_workbench": "返回工作台",
                    "action_open_menu": "打开菜单",
                    "action_refresh": "刷新",
                    "hud_label_reason": "原因",
                    "hud_label_menu": "菜单",
                    "hud_label_action": "动作",
                    "hud_label_route": "路由",
                    "hud_label_diag": "诊断",
                    "hud_label_action_type": "动作类型",
                    "hud_label_contract_type": "契约类型",
                    "hud_label_contract_url": "契约链接",
                    "hud_label_meta_url": "元信息链接",
                    "hud_label_last_intent": "最近意图",
                    "hud_label_trace_id": "追踪 ID",
                    "hud_value_na": "N/A",
                    "action_copy": "复制",
                    "panel_title": "页面暂时无法打开",
                    "reason_nav_menu_no_action": "菜单分组（无可执行动作）",
                    "reason_act_no_model": "动作未绑定模型",
                    "reason_act_unsupported_type": "动作类型暂不支持",
                    "reason_contract_context_missing": "契约上下文缺失",
                    "reason_capability_missing": "缺少能力权限",
                    "reason_unknown": "未知原因",
                    "message_nav_menu_no_action": "当前菜单是目录，暂时没有可进入的子菜单。",
                    "message_act_no_model": "当前动作对应的是自定义工作区，未绑定数据模型。",
                    "message_act_unsupported_type": "当前动作类型暂未在门户壳层支持。",
                    "message_contract_context_missing": "页面缺少契约必需上下文（例如 action_id）。",
                    "message_capability_missing": "当前账号尚未开通该能力。",
                    "message_default": "你可以返回工作台或打开菜单继续操作。",
                },
            },
            "my_work": {
                "schema_version": "v1",
                "texts": {
                    "title": "我的工作",
                    "loading_title": "加载我的工作中...",
                    "hero_subtitle": "聚合待办并直接处理，默认从“待我处理”开工。",
                    "action_refresh": "刷新",
                    "context_preset_prefix": "推荐视图：",
                    "action_clear_preset": "清除推荐",
                    "context_updated_at_prefix": "更新于 ",
                    "retry_failed_prefix": "失败待办 ",
                    "retry_failed_suffix": " 条",
                    "retry_mode_prefix": "模式: ",
                    "retry_replay": "重放结果",
                    "retry_expand_hint": "展开处理",
                    "retry_title": "失败明细",
                    "retry_action_select_failed": "选中失败项",
                    "retry_action_select_all_failed": "选中全部失败项",
                    "retry_action_select_retryable_only": "仅选可重试项",
                    "retry_action_select_non_retryable_only": "仅选不可重试项",
                    "retry_action_retry_failed": "重试失败项",
                    "retry_action_copy_summary": "复制失败摘要",
                    "retry_action_copy_current_view": "复制当前视图",
                    "retry_action_export_failed_csv": "导出失败 CSV",
                    "retry_action_copy_retry_request": "复制重试请求",
                    "retry_action_export_retry_json": "导出重试 JSON",
                    "retry_action_focus_in_main_list": "主列表定位失败",
                    "retry_action_copy_trace": "复制 Trace",
                    "retry_action_ignore": "忽略",
                    "retry_request_preview_title": "重试请求预览",
                    "retry_note_preset_network": "网络抖动",
                    "retry_note_preset_conflict": "并发冲突",
                    "retry_note_preset_dependency": "依赖满足",
                    "retry_note_template_network": "系统重试：网络抖动后重放",
                    "retry_note_template_conflict": "系统重试：并发冲突后重放",
                    "retry_note_template_dependency": "系统重试：依赖状态已满足",
                    "retry_note_label": "重试备注",
                    "retry_note_placeholder": "可选：补充本次重试说明",
                    "retry_capability_prefix": "重试能力：可重试 ",
                    "retry_capability_middle": " / 不可重试 ",
                    "retry_visible_prefix": "当前展示 ",
                    "retry_visible_middle": " / ",
                    "retry_visible_suffix": " 条",
                    "retry_action_expand_all": "展开全部",
                    "retry_action_collapse_all": "收起",
                    "retry_search_placeholder": "筛选失败明细：ID / 原因码 / 消息",
                    "retry_filter_all": "全部",
                    "retry_filter_retryable_only": "仅可重试",
                    "retry_filter_non_retryable_only": "仅不可重试",
                    "retry_group_mode_flat": "平铺显示",
                    "retry_group_mode_grouped": "按原因分组",
                    "retry_action_reset_panel": "重置面板",
                    "retry_reason_distribution_prefix": "失败原因分布：",
                    "retry_action_clear_failed_filter": "清除失败筛选",
                    "retry_group_summary_prefix": "分组摘要：",
                    "retry_group_retryable_prefix": "可重试 ",
                    "retry_action_select_group": "选中此组",
                    "retry_action_retry_group": "重试此组",
                    "retry_unknown_reason_code": "UNKNOWN",
                    "retry_action_copy_single": "复制单条",
                    "retry_action_open_record": "打开记录",
                    "empty_desc": "状态良好。你可以返回工作台查看整体态势，或进入风险驾驶舱继续巡检。",
                    "error_request_failed": "请求失败",
                    "feedback_save_preset_failed": "保存常用筛选失败",
                    "feedback_apply_preset_failed": "应用常用筛选失败",
                    "feedback_clear_preset_failed": "清除常用筛选失败",
                },
            },
            "scene": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "正在加载场景...",
                    "error_fallback": "场景加载失败",
                    "forbidden_title": "能力未开通",
                    "forbidden_message": "当前角色无法进入该场景。",
                    "forbidden_title_permission": "权限不足",
                    "forbidden_message_scope_missing": "当前角色能力范围不包含该场景所需能力。",
                    "forbidden_message_missing_prefix": "缺少能力：",
                    "forbidden_message_missing_sep": "、",
                    "forbidden_detail_reason_left": "（",
                    "forbidden_detail_reason_right": "）",
                    "forbidden_hint_license_prefix": "当前 License：",
                    "forbidden_hint_license_suffix": "，可联系管理员评估升级或开通。",
                    "forbidden_hint_default": "可联系管理员开通对应能力。",
                    "error_scene_target_unsupported": "scene target unsupported",
                    "error_scene_resolve_failed": "scene resolve failed",
                },
            },
            "action": {
                "schema_version": "v1",
                "texts": {
                    "status_loading": "加载中",
                    "status_error": "加载失败",
                    "status_empty": "暂无数据",
                    "status_ready": "已就绪",
                    "intent_title_risk": "风险驾驶舱：先处理严重与逾期风险",
                    "intent_summary_risk": "优先完成分派、关闭或发起审批，避免风险停留在“仅可见”状态。",
                    "intent_action_risk_todo": "待我处理风险",
                    "intent_action_risk_scene": "打开风险场景",
                    "empty_title_risk": "当前暂无风险记录",
                    "empty_hint_risk": "建议转到“我的工作”处理风险待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_risk": "处理风险待办",
                    "secondary_action_risk": "进入风险驾驶舱",
                    "intent_title_contract": "合同执行：优先识别付款与变更风险",
                    "intent_summary_contract": "先看执行率与付款状态，再进入异常合同处理。",
                    "intent_action_contract_todo": "处理合同待办",
                    "intent_action_contract_dashboard": "查看风险驾驶舱",
                    "empty_title_contract": "当前暂无合同记录",
                    "empty_hint_contract": "可前往“我的工作”查看合同待办，或进入风险驾驶舱追踪履约风险。",
                    "primary_action_contract": "处理合同待办",
                    "secondary_action_contract": "查看风险驾驶舱",
                    "intent_title_cost": "成本执行：先回答是否超支",
                    "intent_summary_cost": "优先关注超支金额与超支项，再下钻到具体偏差来源。",
                    "intent_action_cost_todo": "处理成本待办",
                    "intent_action_cost_dashboard": "查看风险驾驶舱",
                    "empty_title_cost": "当前暂无成本记录",
                    "empty_hint_cost": "可前往“我的工作”处理成本待办，或进入风险驾驶舱继续巡检。",
                    "primary_action_cost": "处理超支待办",
                    "secondary_action_cost": "查看风险驾驶舱",
                    "intent_title_project": "项目视角：先判断是否可控",
                    "intent_summary_project": "优先查看风险、审批与经营指标，再决定下一步动作。",
                    "intent_action_project_todo": "查看项目待办",
                    "intent_action_project_dashboard": "进入风险驾驶舱",
                    "empty_title_project": "当前暂无项目记录",
                    "empty_hint_project": "建议进入“我的工作”处理项目待办，或去风险驾驶舱查看全局状态。",
                    "primary_action_project": "查看项目待办",
                    "secondary_action_project": "进入风险驾驶舱",
                    "intent_title_default": "业务列表：先看状态，再执行动作",
                    "intent_summary_default": "通过快速筛选与快捷操作，优先处理最关键事项。",
                    "intent_action_default_home": "工作台",
                    "intent_action_default_my_work": "我的工作",
                    "empty_title_default": "当前视图暂无数据",
                    "empty_hint_default": "建议切换到我的工作或风险驾驶舱继续处理。",
                    "primary_action_default": "去我的工作",
                    "secondary_action_default": "去风险驾驶舱",
                    "empty_reason_default": "可能因为暂无业务数据、当前角色权限受限，或数据尚未生成。",
                    "empty_reason_filter": "可能由当前筛选条件导致无数据，建议先清除筛选后重试。",
                    "empty_reason_wbs": "当前尚未生成执行结构数据，可先在项目立项或工程结构中创建后再查看。",
                },
            },
            "record": {
                "schema_version": "v1",
                "texts": {
                    "loading_title": "Loading record...",
                    "saving_title": "Saving record...",
                    "error_fallback": "Record load failed",
                    "status_loading": "Loading",
                    "status_error": "Error",
                    "status_empty": "Empty",
                    "status_ready": "Ready",
                    "status_editing": "Editing",
                    "status_saving": "Saving",
                    "action_back": "Back",
                    "action_edit": "Edit",
                    "action_save": "Save",
                    "action_cancel": "Cancel",
                    "action_reload": "Reload",
                    "action_download": "Download",
                    "subtitle_editing": "Editing contract fields",
                    "subtitle_ready": "Record details",
                    "ribbon_fallback": "Ribbon",
                    "dev_context_title": "Record Context",
                    "error_load_record": "failed to load record",
                    "error_execute_button": "failed to execute button",
                    "error_save_record": "failed to save record",
                    "chatter_load_failed": "Failed to load chatter",
                    "chatter_post_failed": "Failed to post chatter message",
                    "chatter_upload_failed": "Failed to upload file",
                    "chatter_download_failed": "Failed to download file",
                    "view_node_unsupported_title": "View node unsupported",
                    "view_node_unsupported_message": "Layout nodes are present but renderer support is incomplete.",
                    "banner_saved": "Saved. Changes have been applied.",
                    "summary_status_stage": "项目状态与阶段",
                    "summary_risk": "关键风险摘要",
                    "summary_finance": "资金/产值指标",
                    "next_actions_title": "下一步动作",
                    "next_action_todo": "查看待办",
                    "next_action_risk": "查看风险",
                    "next_action_contract": "查看合同",
                    "next_action_cost": "查看成本",
                    "fallback_details_title": "项目详情",
                    "chatter_title": "协作时间线",
                    "chatter_input_placeholder": "输入评论，支持 @同事 ...",
                    "chatter_posting": "发布中...",
                    "chatter_post_action": "发布评论",
                    "chatter_uploading": "上传中…",
                    "chatter_empty": "暂无协作记录。",
                    "project_phase_unset": "未配置阶段",
                    "project_risk_ok": "正常，暂无高风险告警",
                    "project_risk_critical_prefix": "严重，当前高风险 ",
                    "project_risk_critical_suffix": " 项，需优先闭环",
                    "project_risk_attention_prefix": "关注，当前风险 ",
                    "project_risk_attention_suffix": " 项",
                    "project_output_prefix": "产值 ",
                    "project_output_unset": "产值未配置",
                    "project_pay_prefix": "付款比 ",
                    "project_pay_suffix": "%",
                    "project_pay_unset": "付款比未配置",
                    "readonly_hint_license_prefix": "当前为只读模式（License: ",
                    "readonly_hint_license_bundle_sep": ", Bundle: ",
                    "readonly_hint_license_suffix": "）。如需编辑权限请联系管理员。",
                    "readonly_hint_default": "当前记录处于只读模式，请联系管理员开通写权限。",
                    "missing_capability_prefix": "缺少能力：",
                    "missing_capability_sep": "、",
                    "missing_capability_license_prefix": "；当前 License: ",
                    "action_feedback_failed": "操作失败",
                },
            },
            "scene_health": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Health Dashboard",
                    "subtitle": "可视化查看场景健康状态与自动降级结果。",
                    "loading_title": "Loading scene health...",
                    "error_fallback": "health request failed",
                    "error_reason_required": "reason is required for governance action",
                    "error_governance_failed": "governance action failed",
                },
            },
            "scene_packages": {
                "schema_version": "v1",
                "texts": {
                    "title": "Scene Packages",
                    "subtitle": "导入、导出与审阅已安装的 Scene 能力包。",
                    "loading_title": "Loading packages...",
                    "error_title": "Package operation failed",
                    "error_load_failed": "load packages failed",
                    "error_dry_run_failed": "dry-run failed",
                    "error_import_failed": "import failed",
                    "error_export_failed": "export failed",
                    "error_reason_required": "reason is required for import",
                },
            },
            "usage_analytics": {
                "schema_version": "v1",
                "texts": {
                    "title": "Usage Analytics",
                    "subtitle": "Scene / Capability 使用统计（按公司累计）。",
                    "label_top": "Top",
                    "label_daily_range": "趋势范围",
                    "option_recent_3_days": "最近 3 天",
                    "option_recent_7_days": "最近 7 天",
                    "label_hidden_reason": "隐藏原因",
                    "option_all": "全部",
                    "label_role_slice": "角色切片",
                    "option_all_roles": "全部角色",
                    "label_user_slice": "用户切片",
                    "placeholder_user_slice": "0=全部",
                    "label_scene_prefix": "Scene 前缀",
                    "placeholder_scene_prefix": "如 projects.",
                    "label_capability_prefix": "Capability 前缀",
                    "placeholder_capability_prefix": "如 contract.",
                    "label_export_filtered_only": "仅导出当前筛选",
                    "action_copy_export_params": "复制导出参数",
                    "action_reset_filters": "重置筛选",
                    "action_export_csv": "导出 CSV",
                    "action_refresh": "刷新",
                    "slice_window_prefix": "窗口：",
                    "slice_role_prefix": "角色：",
                    "slice_user_prefix": "用户：",
                    "slice_scene_prefix_label": "Scene 前缀：",
                    "slice_capability_prefix_label": "Capability 前缀：",
                    "summary_scene_open_total": "Scene Open Total",
                    "summary_capability_open_total": "Capability Open Total",
                    "summary_generated_at": "Generated At",
                    "summary_capability_total": "Capability Total",
                    "summary_visible_hidden": "Visible / Hidden",
                    "summary_ready_preview_locked": "Ready / Preview / Locked",
                    "summary_role_codes": "Role Codes",
                    "table_top_scenes": "Top Scenes",
                    "table_scene_key": "Scene Key",
                    "table_count": "Count",
                    "table_top_capabilities": "Top Capabilities",
                    "table_capability_key": "Capability Key",
                    "table_scene_open_last_7_days": "Scene Open (Last 7 Days)",
                    "table_date": "Date",
                    "table_capability_open_last_7_days": "Capability Open (Last 7 Days)",
                    "table_visibility_reason_counts": "Visibility Reason Counts",
                    "table_reason_code": "Reason Code",
                    "table_hidden_capability_samples": "Hidden Capability Samples",
                    "table_key": "Key",
                    "table_reason": "Reason",
                    "table_role_top": "Role Top",
                    "table_role_code": "Role Code",
                    "table_scene": "Scene",
                    "table_capability": "Capability",
                    "table_total": "Total",
                    "table_user_top": "User Top",
                    "table_user_id": "User ID",
                    "loading_title": "Loading usage report...",
                    "error_fallback": "Failed to load usage report",
                    "empty_text": "暂无数据",
                    "error_export_failed": "导出失败",
                    "error_copy_export_params_failed": "复制导出参数失败",
                },
            },
        },
    }
