import type { SuggestedActionKind, SuggestedActionParsed } from './types';

const LABELS: Partial<Record<SuggestedActionKind, string>> = {
  refresh: '立即刷新',
  retry: '重新尝试',
  go_back: '返回上一页',
  open_login: '打开登录页',
  relogin: '重新登录',
  check_permission: '查看权限',
  open_home: '返回首页',
  open_my_work_todo: '打开待办事项',
  open_my_work_done: '打开已办事项',
  open_my_work_failed: '打开失败事项',
  open_my_work_section: '打开工作分区',
  open_my_work: '打开我的工作台',
  open_usage_analytics: '打开使用分析',
  open_locked: '查看受限功能',
  open_preview: '查看预览功能',
  open_ready: '查看可用功能',
  open_hidden: '查看隐藏功能',
  open_scene_health: '查看场景健康',
  open_scene_packages: '打开场景能力包',
  open_projects_list: '打开项目列表',
  open_projects_board: '打开项目看板',
  open_project: '打开项目',
  open_dashboard: '打开工作看板',
  open_record: '打开相关记录',
  open_scene: '打开相关场景',
  open_menu: '打开相关菜单',
  open_action: '打开相关操作',
  open_route: '打开相关页面',
  open_url: '打开链接',
  copy_trace: '复制追踪 ID',
  copy_reason: '复制原因编码',
  copy_message: '复制错误消息',
  copy_error_line: '复制错误摘要',
  copy_action: '复制建议动作',
  copy_json_error: '复制错误详情',
  copy_full_error: '复制完整错误信息',
};

const HINTS: Partial<Record<SuggestedActionKind, string>> = {
  refresh: '刷新最新数据后继续处理。',
  retry: '稍后重新执行当前操作。',
  go_back: '返回上一页继续处理。',
  open_login: '打开登录页重新进入系统。',
  relogin: '重新登录后再继续操作。',
  check_permission: '核对当前角色权限后再尝试。',
  open_home: '回到首页继续处理业务。',
  open_my_work_todo: '直接进入我的工作台待办分区。',
  open_my_work_done: '直接进入我的工作台已办分区。',
  open_my_work_failed: '直接进入我的工作台失败分区。',
  open_my_work_section: '打开指定的工作台分区。',
  open_my_work: '打开我的工作台继续处理事项。',
  open_usage_analytics: '进入使用分析查看功能可见状态。',
  open_locked: '查看当前受限的功能清单。',
  open_preview: '查看当前预览中的功能清单。',
  open_ready: '查看当前可用的功能清单。',
  open_hidden: '查看当前隐藏的功能清单。',
  open_scene_health: '查看场景健康状态与治理信息。',
  open_scene_packages: '进入场景能力包完成治理操作。',
  open_projects_list: '进入项目列表场景。',
  open_projects_board: '进入项目看板场景。',
  open_project: '打开目标项目页面。',
  open_dashboard: '打开系统工作看板。',
  open_record: '打开相关记录并先处理阻塞项。',
  open_scene: '打开相关场景继续处理。',
  open_menu: '打开相关菜单继续处理。',
  open_action: '打开相关操作继续处理。',
  open_route: '打开相关页面继续处理。',
  open_url: '打开提供的链接继续处理。',
  copy_trace: '复制追踪 ID，便于排查问题。',
  copy_reason: '复制原因编码，便于定位问题。',
  copy_message: '复制错误消息，便于沟通处理。',
  copy_error_line: '复制简要错误摘要，便于快速沟通。',
  copy_action: '复制建议动作，便于排查处理。',
  copy_json_error: '复制结构化错误详情，便于技术排查。',
  copy_full_error: '复制完整错误信息，便于完整排查。',
};

export function suggestedActionLabel(parsed: SuggestedActionParsed): string {
  return LABELS[parsed.kind] || '';
}

export function suggestedActionHint(parsed: SuggestedActionParsed): string {
  return HINTS[parsed.kind] || '';
}
